### ISSUE TITLE
Set up AngularJS project

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#1]
- [ ] Use bootstrap
- [ ] Create front page search site https://github.com/fossasia/loklak_search/issues/2
- [ ] Create sub search sites https://github.com/fossasia/loklak_search/issues/3

**Comment by hemantjadon** [comment]
Hi,
I am willing to contribute to this project.
I have a question that why Angular2 is not used instead of angular 1.x ?
I think ng2 is quite stable now with ^rc6 and more future proof.s
Can we think about building from ground up using angular2?

**Comment by hemantjadon** [comment]
Also i want to know that how this project will be different from the [LokLak WebClient](http://loklak.net/).

**Comment by mariobehling** [comment]
@hemantjadon Yes, please use Angular2 and delete anything that is not needed. The webclient was a prototype but it is too bloated and has some strange delay code. We simply need a search page for now and something clean.

**Comment by vanhonit** [comment]
@hemantjadon Please create a branch for angular2. Which programming will you use typescript, javascript es6 or Dart?

**Comment by hemantjadon** [comment]
@vanhonit 
I will like to use typescript.
Also along with it i will like to use `angular-cli` though it is in beta right now but i think it is stable enough to start a new project.

**Comment by vanhonit** [comment]
Look good. But when you use angular-cli please make sure you understand how they structure the project and what component they used.

**Comment by hemantjadon** [comment]
@vanhonit sure i am currently using it in one of my projects and largely understand it.
But still i will again go through the structuring and create a `readme` about the structuring of code for future references.
