### ISSUE TITLE
Add time information to tweet

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#103]
Twitter adds info on when a tweet was posted. Please add date/time info on loklak as well.

![screenshot from 2016-11-03 21 31 11](https://cloud.githubusercontent.com/assets/1583873/19967876/04602c5a-a20d-11e6-9fa9-fbe8a758a05b.png)

**Comment by pranayyelugam** [comment]
@mariobehling  In twitter ,if we click on the date/time a link opens up in a new page showing the tweet.
Does this need to be added here? 
If it is to be added then I think it should be opened as  shown in [#105](https://github.com/fossasia/loklak_search/issues/105)

**Comment by jig08** [comment]
@pranayyelugam This seems like a god feature too.

**Comment by mariobehling** [comment]
@pranayyelugam No, this is not relevant for this issue. As in the screenshot the time/date should be added next to the name/username - here: Knot Unknow @MadeleineS - 3h.

There is another issue here about opening messages in a lightbox: https://github.com/fossasia/loklak_search/issues/105

**Comment by pranayyelugam** [comment]
@mariobehling @jig08   twitter uses twitter timezone settings to find the time since the tweet was posted . Do loklak have any such source where we could get the current time ? or should we use the system  time to get the current time?

**Comment by jig08** [comment]
@Orbiter Your input please.

**Comment by mariobehling** [comment]
There is already a time in the JSON files. This time is in UTC. So, you can get the timezone/time from the browser and take the tweet time from the JSON.

**Comment by Orbiter** [comment]
Hint: please use the timezoneOffset query parameter as documented in http://api.loklak.org/api.html#search

There is also an example on how to use the browser timezone offset, just look into the code of http://api.loklak.org/index.html

**Comment by hemantjadon** [comment]
@mariobehling 
Do we need constantly updating timestamp like implemented right now which changes in every 10s.
I think a constant timestamp should be enough.
Your views please.

@pranayyelugam Want to work on this issue further?

**Comment by pranayyelugam** [comment]
The created_at timestamp in the api json is in UTC and the time from the browser is in UTC so I think there's no need for timezoneoffset here to calculate the time since a tweet was posted.However we should add the timezoneoffset parameter in the API call for location based results.About the updating of the browser time every 10 sec, is there any better approach?. Input please??

**Comment by pranayyelugam** [comment]
Anything more that can be done here ? @mariobehling @hemantjadon
