### ISSUE TITLE
unshorten shortened links to link stubs

### ISSUE THREAD

**Issue by Orbiter** [fossasia/loklak_search#108]
Texts in loklak search results may contain shortened links which point to loklak for unshortening, like: http://loklak.org/x?id=802029515690180608
We want to see those links as original link stubs. To make this possible, the loklak json now contains an ```unshorten``` object, i.e.
```
"text": "Please RT #interiordesign #decoration #architecture #home Best Friday Five Posts of 2015 http://loklak.org/x?id=802029515690180608 https://pic.twitter.com/9EVncMj6AG",
"unshorten": {"http://loklak.org/x?id=802029515690180608": "http://decorationandstyle.com/decoration/..."}
```
Here, the link http://loklak.org/x?id=802029515690180608 is currently rendered as
```
<a href="http://loklak.org/x?id=802029515690180608">http://loklak.org/x?id=802029515690180608</a>
```
but using the ```unshorten``` object, it is possible to translate the link back into ```http://decorationandstyle.com/decoration/...```
The resulting link in the html should be
```
<a href="http://loklak.org/x?id=802029515690180608">http://decorationandstyle.com/decoration/...</a>
```

To do:
- for each key in the ```unshorten``` object, try to match this with a substring in ```text````
- replace the link text for that link with the value of the object in ```unshorten```

**Comment by shubhsingh594** [comment]
hi all, can i work on this one?

**Comment by mariobehling** [comment]
Sure, please go ahead.

**Comment by jig08** [comment]
@shubhsingh594 Also join the specific team so that this issue can be assigned to you :)

**Comment by Orbiter** [comment]
Please read again the requirement to understand that the replacement must be done only in the anchor text, not the anchor link.

**Comment by shubhsingh594** [comment]
@orbiter  okay yeah, i assumed they are valid links, will make another pull request
