### ISSUE TITLE
Ensure the root URL of the project shows the start page of the project

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#11]
The root directory of the project should show the start page of the project. 

If you are unsure how to implement this, please compare this to other Angular2 repositories like: https://github.com/tjvantoll/groceries and the website here https://github.com/tjvantoll/groceries

Also check out: https://github.com/angular/angular-cli

**Comment by hemantjadon** [comment]
I think this is solved in #15.
Please specify if there are other requirements of this.. :)
