### ISSUE TITLE
Insufficient Documentation

### ISSUE THREAD

**Issue by ankitrgadiya** [fossasia/loklak_search#119]
There is no information provided on how to install it.

**Comment by hemantjadon** [comment]
Hi @ankitrgadiya thanks for raising the issue.

`Loklak Search` project is very much in its initial phase of development thus there some insuffitient documentation for installing and getting used to the architecture.

Well the installation is very simple, 

* just clone the repository, add the install 

* node >= 6

* npm >=3

* then run `npm install` while in the project directory this will install all the required dependencies.

* Then simply run `ng serve` to run on your local machine.

* If all went well there will be local server running at `http://localhost:4200`

**Comment by jig08** [comment]
@hemantjadon I suggest you to add a `installation guide` in the repo for new contributors :)

**Comment by ankitrgadiya** [comment]
@jig08 I'll do that once my own version will work. 
@hemantjadon Localhost is working fine.
Github pages version is currently building. But yeah I'll do that soon.

**Comment by hemantjadon** [comment]
@jig08 Can we add it as a task?

**Comment by jig08** [comment]
@hemantjadon That'll be great !

**Comment by ankitrgadiya** [comment]
Then I'm gonna claim that next.

**Comment by mariobehling** [comment]
Ok, great. Would be happy if the setup works out! I also added a task to work on documentation for GCI here: https://codein.withgoogle.com/tasks/5747664924704768/

**Comment by ankitrgadiya** [comment]
Okay working on it!

**Comment by jig08** [comment]
wrt PR https://github.com/fossasia/loklak_search/pull/122 closing this.
