### ISSUE TITLE
Add a simple search button on front page and make start page accessible from root directory

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#12]
The goal of the issue is to make the start page accessible from the root at https://fossasia.github.io/loklak_search/ and show a simple search button.

**Comment by hemantjadon** [comment]
@mariobehling @sainiak009 

* Both the issues this and #11 can be solved using `ng github:pages:deploy`.

* But the thing to note is the deployment requires the complete `webpack build` which generates the the transpiled and gziped `.ts` and `.scss` are also preprocessed and compiled.

* These files along with `assets` like `images/fonts` etc. are stored on main branch.

* In our project the `gh-pages` branch holds all the code and according to me both the dev code and compiled code in same branch will cause conflicts and confusion.

* So i think a new branch must be created for development process, followed by cleaning of gh-pages from develpoment code, then the transiotion and deployment will be simple.

* For sample please refer https://github.com/hemantjadon/Angular2-test/

   * See the differrence in `master` and `gh-pages` branches.
   
   * The development code is simply placed in master, and site is deployed simply in `gh-pages`.

   * If any other process can be applied, please let me know.

**Comment by mariobehling** [comment]
@hemantjadon Good job pointing all this out. Yes, please proceed to put up dev code to master and deployment to gh-pages. Is there any way to deploy updated code from master to deployment version on gh-pages?

**Comment by hemantjadon** [comment]
@mariobehling 
> Is there any way to deploy updated code from master to deployment version on gh-pages?

Are you refering to Continuous Deploy script hooked up with `travis` or some some other platform which will run the command `ng github-pages:deploy` whenever there is a `passing build` merged with `master`.

* Also there is no `master` branch `upsteram` in the repository, please create that so that workflow can be completed.

**Comment by mariobehling** [comment]
> Are you refering to Continuous Deploy script hooked up with travis

Yes, let's go that way.

> Also there is no master branch

Done.

**Comment by hemantjadon** [comment]
@mariobehling 

* I have written a bash script for the Continuous Deployment to build continuously whenever there is commit on master but i don't know why its failing on the last step, During testing with a test repo

```bash

#!/bin/bash

SOURCE_BRANCH="master"
TARGET_BRANCH="gh-pages"

# Pull requests and commits to other branches shouldn't try to deploy, just build to verify
if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "$SOURCE_BRANCH" ]; then
    echo "Skipping deploy;"
    exit 0
fi

# Save some useful information
REPO=`git config remote.origin.url`
SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
SHA=`git rev-parse --verify HEAD`

ENCRYPTED_KEY_VAR="encrypted_${ENCRYPTION_LABEL}_key"
ENCRYPTED_IV_VAR="encrypted_${ENCRYPTION_LABEL}_iv"
ENCRYPTED_KEY=${!ENCRYPTED_KEY_VAR}
ENCRYPTED_IV=${!ENCRYPTED_IV_VAR}
openssl aes-256-cbc -K $ENCRYPTED_KEY -iv $ENCRYPTED_IV -in deploy_key.enc -out deploy_key -d

chmod 600 deploy_key
eval `ssh-agent -s`
ssh-add deploy_key

git clone $REPO repo
cd repo
git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
cd ..

# Cleanup
rm -rf repo/* || exit 0
cd repo
git add --all
git commit -m "Travis CI Clean Deploy : ${SHA}"

git checkout $SOURCE_BRANCH

# Fresh build
npm install
ng build
mv dist/ travis/  # HACK : against .gitignore
git add travis/
git commit --amend --no-edit || exit 0
git push --force $SSH_REPO $TARGET_BRANCH

```

* It commits in the last line but never pushes the changes the script just closes.

* I have not written much bash scripts, so there may be rookie mistake :P

**Comment by hemantjadon** [comment]
```bash

#!/bin/bash
# set -e # Exit with nonzero exit code if anything fails

SOURCE_BRANCH="master"
TARGET_BRANCH="gh-pages"

# Pull requests and commits to other branches shouldn't try to deploy, just build to verify
if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "$SOURCE_BRANCH" ]; then
    echo "Skipping deploy;"
    exit 0
fi

# Save some useful information
REPO_NAME=`git rev-parse --show-toplevel`
REPO=`git config remote.origin.url`
SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
SHA=`git rev-parse --verify HEAD`

ENCRYPTED_KEY_VAR="encrypted_${ENCRYPTION_LABEL}_key"
ENCRYPTED_IV_VAR="encrypted_${ENCRYPTION_LABEL}_iv"
ENCRYPTED_KEY=${!ENCRYPTED_KEY_VAR}
ENCRYPTED_IV=${!ENCRYPTED_IV_VAR}
openssl aes-256-cbc -K $ENCRYPTED_KEY -iv $ENCRYPTED_IV -in deploy_key.enc -out deploy_key -d

chmod 600 deploy_key
eval `ssh-agent -s`
ssh-add deploy_key

git clone $REPO repo
cd repo
git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
cd ..

rm -rf repo/* || exit 0
cd repo
git add --all
git commit -m "Travis CI Clean Deploy : ${SHA}"

git checkout $SOURCE_BRANCH

npm install
ng build --prod --base-href /Angular2-test/  # Has to find the repo-name dynamically instead of hardcoding
git checkout $TARGET_BRANCH
mv dist/* .
git add .
git commit -m "Travis CI Clean Deploy : ${SHA}"  # This commit is not good instead --amend must be think about
git push --force $SSH_REPO $TARGET_BRANCH

```

* I think something like this will work, Not so sure, but its working on my test repo.

**Comment by hemantjadon** [comment]
@mariobehling @daminisatya 

This process will require the generation of `deploy_key` and its inclusion in repository.
https://gist.github.com/domenic/ec8b0fc8ab45f39403dd#get-encrypted-credentials for reference.

**Comment by mariobehling** [comment]
Ok, very good progress on this issue. Could you show us the outcome on your repo, please?

**Comment by sainiak009** [comment]
@hemantjadon Good progress. Let me know if I can assist you in any way :)

**Comment by hemantjadon** [comment]
@mariobehling 
* The repo is on my github https://github.com/hemantjadon/Angular2-test
   
   * Please see `gh-pages` branch, it contains compiled and minified version of scripts and assets.
   
   * On `master` you can see the `deploy_key.enc` the `private` part of `ssh key` encrypted with `travis cli`, the `public` part is set up on github as `deploy key`.

   * In `.travis.yml` see `the `after_success` token running `deploy.sh`

* The last build is at https://travis-ci.org/hemantjadon/Angular2-test
   
   * See the deploy.sh run part , (It's a pretty long log so just scroll to bottom to see the actual push by travis to `gh-pages` of the repo.

   * First few lines of `deploy.sh` part of the build state the proper `decryption` and `chmod` of the `ssh key`.

* The output of the repo can be seen at https://hemantjadon.github.io/Angular2-test/

* Few screenshots attached : 

* Pushing Code on master

![screen shot 2016-10-09 at 2 45 43 pm](https://cloud.githubusercontent.com/assets/11755543/19219466/86140fa4-8e31-11e6-9d40-67d1f56d831b.png)

* Travis CI build started

![screen shot 2016-10-09 at 2 44 55 pm](https://cloud.githubusercontent.com/assets/11755543/19219469/933ae086-8e31-11e6-81f8-43b3efd4a03e.png)

* `deploy.sh` started (after_success)

![screen shot 2016-10-09 at 2 47 06 pm](https://cloud.githubusercontent.com/assets/11755543/19219470/937b97ca-8e31-11e6-8edc-eb3099ab48cf.png)

* Commit to `gh-pages` by Travis
![screen shot 2016-10-09 at 2 49 09 pm](https://cloud.githubusercontent.com/assets/11755543/19219471/937fd09c-8e31-11e6-8341-676515423528.png)

* Hope this helps. :)

**Comment by mariobehling** [comment]
Hi, no need to make screenshots of code or tests. We can see all that. Let's keep it short. Hope it works out with the implementation of the search to finish this issue. Cheers.

**Comment by hemantjadon** [comment]
Ok, i'll keep it as short as possible from now on.
So should I open up a PR for this??

**Comment by mariobehling** [comment]
Yes, you can make a pull request, but as far as I can see the current work does not solve the issue entirely. Still no search implementation. Goal is a simple search button, that puts out dtaa, no logo or any other information is required.
