### ISSUE TITLE
Redux based architecture

### ISSUE THREAD

**Issue by hemantjadon** [fossasia/loklak_search#123]
Currently our application has a basic functionality and basic components still there are a lot of cross component state dependencies.
We have service but our components are unable to share their state and are pretty much have their own state and mutate it.
As our application grows this might be huge bottleneck, and might lead to a confusing code base in an application of decent size.

The simple solution is using  **Redux** based architecture for the state management using `@ngrx/store` and `@ngrx/effects`. 
This will not only have a good application structure but also a huge advantage in easier to understand and easier to test code base.

**Comment by hemantjadon** [comment]
@mariobehling  I am currently working on this application structure.

**Comment by mariobehling** [comment]
@hemantjadon Thank you. Personally I am not familiar with it, but if someone else has feedback very welcome. If you think it is useful, please proceed. If it continues to run on Github pages would be great.

**Comment by hemantjadon** [comment]
@mariobehling It will definitely work on `gh-pages` or wherever we want, this is not change of framework but the architecture in which data travels across the application. I think it will be useful to have independently testable components and services.
If someone else has any feedback or opinions I will be happy to incorporate them. :)
