### ISSUE TITLE
Hashtag links do not link to top of page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#129]
Right now clicking to a hashtag on the bottom of the page does not bring the user to the top of search results. Please ensure it links to the top of pages.

![screenshot from 2016-12-16 16-31-44](https://cloud.githubusercontent.com/assets/1583873/21257952/48e57ecc-c3ad-11e6-8bbf-77851338c1bd.png)

**Comment by uttu357** [comment]
The bug is the same as #85

**Comment by hemantjadon** [comment]
Duplicate of #85. can be closed.
