### ISSUE TITLE
CSS framework.

### ISSUE THREAD

**Issue by hemantjadon** [fossasia/loklak_search#140]
Currently we are using Bootstrap as the CSS framework but it is not being used widely across the application. also for proper function of bootstrap, we have to include the `jQuery` which is not quite necessary in the application. As angular in itself should be used for DOM manipulation not any external framework.

We can remove the framework and go on with either no framework approach or go with `angular/material2` though this project is in alpha now we can implement this later in 1-2 months.

* [ ] Remove Bootstrap
* [ ] Remove jQuery
* [ ] Fix the places where the UI breaks after applying the changes.

**Comment by uttu357** [comment]
@hemantjadon i would like to work on this..

**Comment by hemantjadon** [comment]
Yeah sure @uttu357.
Please share how will you proceed, ie. going without framework at all, or using `angular/material2`?

**Comment by uttu357** [comment]
Without framework would be a better option in my opinion... keep it simple and good..

**Comment by hemantjadon** [comment]
@uttu357  Yeah sure go ahead. As a part of the issue you have to fixup all the places where the UI breaks after removing the Bootstrap and jQuery.

**Comment by uttu357** [comment]
sure.. :+1:

**Comment by hemantjadon** [comment]
@uttu357 Any updates regarding this?

**Comment by uttu357** [comment]
Working on it will file a PR soon enough.. Sorry for the delay..

**Comment by hemantjadon** [comment]
@uttu357 No problems i wanted to know that is there any problem in which I can help.

**Comment by uttu357** [comment]
@hemantjadon I was thinking that we should move the individual styles for each component into a single folder src/styles/partials/ as partial scss files so that we can develop a uniform style using variables, mixins present in the other partials?

**Comment by hemantjadon** [comment]
@uttu357 No I don't think so, the individual styles belong to each component, and its not logical to move them same folder.

What you can do is, make a `partials` file in maybe `shared/styles/theme.css` and apply common theme styles there (Only theme related styles) Nothing related to individual components must be out of there context. 

There are many reasons for this: 

* Harder to style individual components.

* Overlapping styles.

* Most importantly `shadow` boundary of the components will be violated if `ViewEncapsulation.Native` is used and you will not be able to style externally.

**Comment by uttu357** [comment]
ohkz.. :+1:
