### ISSUE TITLE
Unmodified links in the lightbox.

### ISSUE THREAD

**Issue by Achint08** [fossasia/loklak_search#141]
All the feeds with links particularly in the last are replaced by loklak.org links as returned from Api Response(which redirect to the same link)  in the feed lighbox. Moreover , the "View on Twitter" is not working.
![screen shot 2016-12-23 at 3 50 54 am](https://cloud.githubusercontent.com/assets/15813932/21442353/7155c8a6-c8c3-11e6-8491-e8246bfa4d96.png)
![screen shot 2016-12-23 at 3 52 39 am](https://cloud.githubusercontent.com/assets/15813932/21442354/7159cf78-c8c3-11e6-87d8-7c7af06ab02b.png)

**Comment by hemantjadon** [comment]
Please followup on #105 (Parent Issue)

**Comment by mariobehling** [comment]
Closing this in favor of: https://github.com/fossasia/loklak_search/issues/105
