### ISSUE TITLE
Lightbox needs to be made responsive.

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/loklak_search#142]
![capture](https://cloud.githubusercontent.com/assets/11540785/21443355/8333bcd4-c8ca-11e6-8def-98ba9a9fb635.PNG)

Either the size could be reduced or the tweet can use full height and width of the device.

**Comment by hemantjadon** [comment]
@rishiraj824 Thanks for pointing this out, please check #105 out for followup on this

**Comment by mariobehling** [comment]
Closing this in favor of: https://github.com/fossasia/loklak_search/issues/105
