### ISSUE TITLE
Lightbox pops up when clicking on link

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#144]
Currently the light box pops up when the user clicks a link in a tweet.

Expected behavior: Linked page should be loaded instead of lightbox.

**Comment by Achint08** [comment]
Solved this issue in PR #145

**Comment by hemantjadon** [comment]
@Achint08 doesn't seem to be fixed to me in your demo site. Please check

**Comment by Achint08** [comment]
@hemantjadon Now the lighbox will come up when clicked on near the text area.

**Comment by hemantjadon** [comment]
@Achint08 I don't think this is what is required here. We want to stop the bubbling of the click event when the inner a tags are clicked. You have attached the click handler to the Paragraph I don't think it fixes this issue.

**Comment by Achint08** [comment]
@hemantjadon  ok sure. I removed the Commit in the PR. Will work on that later.

**Comment by adnrs96** [comment]
Hey @hemantjadon i would like to work on this, infact i have fixed this and would like to create a PR.
Please add me to codeheat github team

**Comment by hemantjadon** [comment]
@mariobehling Please add @adnrs96 to the team :)

**Comment by adnrs96** [comment]
@hemantjadon Should i wait until added to the team or create PR right away.
Please review whether the issue is resolved successfully. I have a version running in github pages at link 
https://adnrs96.github.io/loklak_search/
Thanks in advance

**Comment by hemantjadon** [comment]
Open up the PR there is no harm in it. 👍

**Comment by mariobehling** [comment]
@adnrs96 Please accept the invitation to the team at https://github.com/fossasia.org
