### ISSUE TITLE
Add a contact form as a lightbox

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#152]
On the page http://loklak.fossasia.org/contact there is a contact button. Please add a lightbox to the system, that opens on clicking "contact" on the page.

**Comment by Achint08** [comment]
I would like to work on this. :)

**Comment by hemantjadon** [comment]
Okay Anchit I am assigning it to you :)

**Comment by Achint08** [comment]
@mariobehling  @hemantjadon  What thing you would like me to add in the lightbox?

**Comment by hemantjadon** [comment]
Well I don't know why but your name is not appearing in list. Still you start work on this.

**Comment by Achint08** [comment]
@mariobehling What I think about in the contact form is to add
1.)Name 
2.)Email
3.)Options for Issue type 
      a.)Report  abusive content
      b.)Report a safety issue 
4.)a text input form for explaining it.
Kindly tell me if I am adding the correct options?

**Comment by jajodiaraghav** [comment]
What would happen when the user submits the form? Where should we submit the data?
Thanks in advance

**Comment by BrainBuzzer** [comment]
@mariobehling Would you please tell where the data should be submitted? Or should there be another issue on loklak server repo for implementing that api?

**Comment by Achint08** [comment]
This issue can be closed now. via #162
