### ISSUE TITLE
Add deploy key to travis

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#16]
Please help to finish the deployment to gh-pages.

**Comment by hemantjadon** [comment]
@mariobehling 
I have added The Deploy key to github, but what i also need is access to add environment variables to Travis CI which will be required to decrypt the private part of the ssh key during `deploy.sh`

**Comment by mariobehling** [comment]
@hemantjadon Please post the variables that need to be added here.

**Comment by hemantjadon** [comment]
@mariobehling  sorry for bothering it was some issue with cli not able to sync settings its done now :)

**Comment by mariobehling** [comment]
@hemantjadon Ok, what is missing to get the site up and running on gh-pages?

**Comment by hemantjadon** [comment]
@mariobehling Its done now running on `gh-pages` :)

**Comment by mariobehling** [comment]
Ok, great.

So, lets get some results going. Please help to show results on a results page: https://github.com/fossasia/loklak_search/issues/17
