### ISSUE TITLE
Make the reply, like and retweet options work.

### ISSUE THREAD

**Issue by Achint08** [fossasia/loklak_search#161]
I searched about it a lot. There are certain code to make it work. But there will be a popup window to use these options. Any other way  @hemantjadon  @mariobehling ?

**Comment by mariobehling** [comment]
@Achint08 Yes, would be nice to get it working. Could you outline your idea, please? We are aiming of keeping the dependency on twitter APIs low though. What are your ideas?

**Comment by Achint08** [comment]
We can link it  to anchor tags with link "https://twitter.com/intent/{{like/retweet}?tweet_id={{id_str property of API response}}" for like and retweet.
and reply link to https://twitter.com/intent/tweet?in_reply_to=6{{id_str property of api response}}&ref_src=twsrc%5Etfw&tw_i={{id_str property of api response}}&tw_p=tweetembed.

**Comment by Elgayar** [comment]
Solved! #169
