### ISSUE TITLE
Simplify "Search More" style

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#163]
The "search more" on the bottom introduces a new blue color and has a border element, that we do not find anywhere else on the site. 

Please simplify the style to go inline with the page design
* [ ] Take out the background and border
* [ ] Only show the "Show More" in blue (as it is now) and bold
* [ ] Also ensure the cursor changes when scrolling over

![screenshot from 2017-01-03 17-38-52](https://cloud.githubusercontent.com/assets/1583873/21615090/4d36383a-d1dc-11e6-81be-3c9b17c3344d.png)

**Comment by uttu357** [comment]
Would like to fix this..

**Comment by mariobehling** [comment]
Please check the live site. It is not working for me yet.

**Comment by hemantjadon** [comment]
@mariobehling please can you test this again. Even if it is the issue it is not because of #165 as it only have `css` changes.

**Comment by mariobehling** [comment]
@hemantjadon Thanks. Looks good.
