### ISSUE TITLE
Only show "Search More" when there actually is "More"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#164]
Currently the "Search More" button also shows up, even when there are not more results. Clicking on the button results in no action.

Please only show "Search More" when more results are available.

**Comment by uttu357** [comment]
Would like to fix this issue..

**Comment by hemantjadon** [comment]
@mariobehling @uttu357 
This was the issue which I faced while writing the code, for pagination. The problem is I was not able to find the `number` of results. So was unable to check whether all results have been shown or not.

**Comment by hemantjadon** [comment]
@uttu357 Working on this??

**Comment by uttu357** [comment]
@hemantjadon Yeah working on it! will file a PR soon.. :+1:

**Comment by uttu357** [comment]
@hemantjadon To implement this I was thinking that as we ask for 30 records at a time; if on clicking on "See More" less than 30 records are returned then we can set `searchMore: false` in pagination state which will be used to detect if we have to show searchMore or not! Your suggestions?
