### ISSUE TITLE
Document how to set up a working system - including showing search results

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#166]
There are a number of people who have achieved to set up the service. However, the search result functionality does not seem to work. Please document how to get the service working.

**Comment by mariobehling** [comment]
@uttu357 I am not seeing GitHub pages of others that show search results. Any link for an example?

**Comment by uttu357** [comment]
Open https://uttu357.github.io/loklak_search/search?query=javascript and follow step 5 of https://github.com/fossasia/loklak_search/blob/master/README.md#for-deploying-with-github-pages. The search should work then.

**Comment by Elgayar** [comment]
https://elgayar.github.io/loklak_search/
Mine works as well, however as @uttu357 said, step 5 is the key for the search results to work.

**Comment by uttu357** [comment]
@mariobehling Can this issue be closed or it requires more information?

**Comment by hemantjadon** [comment]
I think this can be closed for now :)
