### ISSUE TITLE
Implement Live Results Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#17]
Parent Issue: https://github.com/fossasia/loklak_search/issues/3

Please implement a live result page for searches.

**Comment by hemantjadon** [comment]
@mariobehling a very simple search page already up and running 
Please check it out by submitting query on home page.

I am on my way to implement live lazy loading of results.

**Comment by mariobehling** [comment]
Please provide examples. I do not see anything loading and just get an empty page. Could you also get rid of the "loading" message, please?

**Comment by hemantjadon** [comment]
@mariobehling 
I got the issue ... 

* The github.io page is served over `https` and the api is called over `http`, so browser raises a warning/error. : MixedContent

* You can temporarily view the results by  Allow the loading of the `unsafe scripts`, right corner of `url bar` in browser.

* But github `enforces` us to use `https` till we are using their domain `fossasia.github.io` (can be seen in gh-pages part of reopsitory settings)

* I don't know that is there any way in which we can work around this, but this issue needs help.

**Comment by mariobehling** [comment]
> But github enforces us to use https

This is not correct as far as I can see. https is activated somewhere.

It is working fine on another repo: http://fossasia.github.io/open-event-webapp/

**Comment by hemantjadon** [comment]
> This is not correct as far as I can see. https is activated somewhere.

> It is working fine on another repo: http://fossasia.github.io/open-event-webapp/

Yes github enforced it since `15th June 2016` https://help.github.com/articles/securing-your-github-pages-site-with-https/

I viewed the project history of that repo and it had a gh-pages branch before.

**Comment by mariobehling** [comment]
Ok, I added a CNAME for http://loklak.fossasia.org.

Let's go with this for the moment. 

Please make the site work on that domain.

**Comment by hemantjadon** [comment]
@mariobehling 
The settings are not showing the CNAME specified by you. 
Is it changed intensionally ?? 
![sc](https://cloud.githubusercontent.com/assets/11755543/19267543/f77353fc-8fcc-11e6-858b-0fa193feb128.jpg)

**Comment by jig08** [comment]
@mariobehling @hemantjadon I just pushed `CNAME` file to `gh-pages` and it now shows `Your site is published at http://loklak.fossasia.org/`. 

Go ahead with making the site go live at this domain, Cheers !

**Comment by mariobehling** [comment]
thank you.

**Comment by mariobehling** [comment]
Please check out this issue, that you could do next: https://github.com/fossasia/loklak_search/issues/19
