### ISSUE TITLE
Improving Footer

### ISSUE THREAD

**Issue by pipix51** [fossasia/loklak_search#171]
The Developers tab seems slightly misleading as it points towards loklak.org (loklak_server). Should this me renamed? And should there be a tab to link to the loklak_search GitHub repository?

**Comment by hemantjadon** [comment]
I don't think this is relevent right now. Anything required here @mariobehling

**Comment by mariobehling** [comment]
Ok, as we are at this, maybe let's do it: Please change as follows
* [ ] Developers link to http://dev.loklak.org
* [ ] On the right next to developers add "API" with link to http://api.loklak.org
* [ ] Next to API add "Apps" and link to http://apps.loklak.org

**Comment by Bhargavasomu** [comment]
I would like to work on this issue
