### ISSUE TITLE
Show a loading bar while searching

### ISSUE THREAD

**Issue by Elgayar** [fossasia/loklak_search#172]
I think it's important to add a loading bar so that the user knows whether the problem is from our side or from his side, because when the screen is all white, it is confusing whether there is a server fault or my browser isn't working.

* [ ] Design/ Choose the loading animation.
* [ ] Hook them To the section.
* [ ] Show it while loading the results

**Comment by Bhargavasomu** [comment]
I would like to work on this issue

**Comment by uttu357** [comment]
@Bhargavasomu are you working on this?

**Comment by rishiraj824** [comment]
@mariobehling we can have a loading bar like Youtube, when the video loads. Thte one below the URL bar. We can choose the loklak's color. Would like to work on it, if it's not assigned.

**Comment by mariobehling** [comment]
@rishiraj824 Sounds great, but could you help to finalize the sidebar first, please? Currently the sidebar only shows the outcome for the first search. Thank you.

**Comment by mariobehling** [comment]
https://github.com/fossasia/loklak_search/issues/200

**Comment by rishiraj824** [comment]
Yes will do that. @mariobehling

**Comment by mariobehling** [comment]
@Elgayar I think the same icon loading animation that appears on the "search more" area is sufficient.

**Comment by Elgayar** [comment]
It's fine, this could be something an extra feature to enhance the website's UI.. @mariobehling

**Comment by yasirunilan** [comment]
can I work on this if anyone is not working on it?

**Comment by Jatinbalodhi96** [comment]
Have someone started to work on this issue?

**Comment by yasirunilan** [comment]
@Jatinbalodhi96 yes I'm working on this.

**Comment by Jatinbalodhi96** [comment]
thats great @yasirunilan just wanted to know
