### ISSUE TITLE
Add info line below search box on front page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#175]
The current page on loklak has an info line below the search box. Please add a similar below the search box on the front page. Use the following text:

Use #hashtag; "search text" for exact matches; near:location finds messages near a location; @user finds user mentions, from:user shows messages of a user

**Comment by pipix51** [comment]
I would like to work on this issue

**Comment by mariobehling** [comment]
![screenshot from 2017-01-08 01-50-50](https://cloud.githubusercontent.com/assets/1583873/21746431/202f038c-d545-11e6-9a6b-c1bcb1f8fcf5.png)

On a second view, the first implementation has a font size that is too small.

* [ ] Please increase the font size a bit
* [ ] Also center the text and move it just below the search bar

**Comment by kaushikgunda** [comment]
@mariobehling I would like to work on this issue.

**Comment by pipix51** [comment]
@kaushikgunda Sorry, I did not notice your comment and sent a pull request which fixed the issue...Anyways, I submitted the previous pull request; it should be my responsibility to fix any issues which occur with the PR.

**Comment by mariobehling** [comment]
Please take a very slight light grey for the highlights.

**Comment by meets2tarun** [comment]
I will do this task
