### ISSUE TITLE
Show loading icon after user clicks on "Show more"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#176]
Currently the user does not get feedback if there is a process running after he/she clicks on "Show more" at the end of a search result. The user often then clicks again and it seems like nothing is happening. Suddenly more results show up.

Please show a loading icon after the user has clicked "Show More" to indicate that a process is running.

**Comment by uttu357** [comment]
I would like to fix this. :+1:

**Comment by uttu357** [comment]
@mariobehling this issue can be closed now.
