### ISSUE TITLE
Unclear files in repo

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#18]
There are some files in the repository, where the usage is not clear.

@hemantjadon Any idea?

![screenshot from 2016-10-11 12 20 51](https://cloud.githubusercontent.com/assets/1583873/19267113/4ab8402e-8fad-11e6-883a-bedd671ad376.png)

**Comment by hemantjadon** [comment]
Yeah those files bugged me too. From my observation those are `bootstrap font/glyphs` related stuff. I don't know why the build process is emitting them in root directory.

**Comment by hemantjadon** [comment]
@mariobehling 
Does this issue requires more info ??

**Comment by uttu357** [comment]
@hemantjadon @mariobehling I believe this issue is irrelevant now as we are not using bootstrap font/glyphs anymore and can be closed?

**Comment by hemantjadon** [comment]
Closing this as this is irrelevent now.
