### ISSUE TITLE
Small design improvements

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#186]
Please improve as follows:
* use loklak in small (not capital letters)
* on start page write loklak search! instead of Loklak Search!
* on top left subpages write loklak using Courier New font
![screenshot from 2017-01-08 21-19-22](https://cloud.githubusercontent.com/assets/1583873/21753208/43d9b388-d5e8-11e6-99ec-d156aa6349d0.png)
* About, Contact, Terms pages use Courier New as a font for "loklak" on the top left

**Comment by Shivang-Bhandari** [comment]
Hi @mariobehling I would like to work on this issue.
