### ISSUE TITLE
Implement tweet frequency in sidebar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#188]
The tweet frequency will show how a certain keyword mentioning develops over time.

![screenshot from 2017-01-08 23-23-22](https://cloud.githubusercontent.com/assets/1583873/21754109/a5b3682c-d5f9-11e6-8254-728923db0323.png)

**Comment by rishiraj824** [comment]
Will implement this on the infobox added. @mariobehling

**Comment by yasirunilan** [comment]
For this do we have to configure the loklak server also?
Or is it just a front end work?

**Comment by rishiraj824** [comment]
@yasirunilan I think the response we are receiving right now is sufficient to plot the histogram.

**Comment by yasirunilan** [comment]
can I work on this one if any one is not assigned?

**Comment by Achint08** [comment]
@rishiraj824 Hello. I was looking towards this tweet frequency chart . I found this somewhere. I thought it would help you somewhere.
https://www.angularjs4u.com/angularjs2/top-20-angular-2-charts-graphs/ 
You should also checkout this :- 
https://scotch.io/tutorials/interactive-angular-2-charts-with-zingchart .
:)

**Comment by rishiraj824** [comment]
@Achint08 I've added ng2-charts/chart.js in the side-bar. I'll put a PR. Please have a look at the code. It needs to be hooked up with the backend data.

**Comment by mariobehling** [comment]
Thanks. Next steps in this issue:

* [ ] please change the color from pink to gray which is used in the top bar. 
* [ ] also ensure the table fits in the box. At the moment there is no padding on the right hand side. Thank you.

**Comment by rishiraj824** [comment]
@mariobehling I'll work on this and fix them asap.
