### ISSUE TITLE
Implement search similar to market leader design

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#19]
* [ ] Implement Google theme (with loklak logo)
* [ ] At first glance show search bar in middle
* [ ] Implement moving up of search area to top left on typing start similar to Google

![screenshot from 2016-09-04 22 34 32](https://cloud.githubusercontent.com/assets/1583873/18233778/68b46cc6-72f0-11e6-8241-fb050fa05663.png)

**Comment by mariobehling** [comment]
Please also correct capitals in "I'm feeling Awesome!" to "I'm feeling awesome!".

**Comment by hemantjadon** [comment]
@mariobehling 
It's done now :)

**Comment by jig08** [comment]
@hemantjadon In PR number ?

**Comment by jig08** [comment]
Appears as directed, closing this issue.

<img width="1275" alt="screen shot 2016-10-12 at 9 16 11 pm" src="https://cloud.githubusercontent.com/assets/9291400/19316985/20623144-90c1-11e6-85db-4476b00807d8.png">
