### ISSUE TITLE
Match the width of areas

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#196]
In the recent addition of the sidebar the proportions of the areas were changed a bit. Please match the areas to correspond with the Google theme.
* [ ] Make the search results in the same area width as the search results
* [ ] Make the sidebar in the same area and width as on the Google theme

![screenshot from 2017-01-11 02-25-29](https://cloud.githubusercontent.com/assets/1583873/21831667/c8bb8b6c-d7a5-11e6-8e56-78730d79ac93.png)

**Comment by uttu357** [comment]
Would like to fix this..

**Comment by mariobehling** [comment]
Thank you. Please help with a few more small improvements:

* [ ] The width of the tweet content area should be the same as the search bar in all resolutions (please compare to Google)
* [ ] The distance of the content area to the upper gray menu bar should be larger
* [ ] Please reduce the space between blue profile icons and the following info
![screenshot from 2017-01-11 11-01-16](https://cloud.githubusercontent.com/assets/1583873/21844130/ca990084-d7ed-11e6-914a-aaf18160ef5f.png)

**Comment by uttu357** [comment]
Will do them asap. :+1:

**Comment by uttu357** [comment]
This issue can be closed now.
