### ISSUE TITLE
Create front page search site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#2]
A sample of the front page search site below. 

![screenshot from 2016-09-20 18 16 36](https://cloud.githubusercontent.com/assets/1583873/18684567/f3a47d9a-7f74-11e6-9d6b-cdc62afbed66.png)

**Comment by hemantjadon** [comment]
Resolved in #10

**Comment by mariobehling** [comment]
Does not see that it is resolved. https://fossasia.github.io/loklak_search/ does not show the site.

**Comment by hemantjadon** [comment]
@mariobehling I think this issue is resolved and can be closed. Your inputs please.
