### ISSUE TITLE
Implement relevant sidebars for search of from:user

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#203]
The sidebar displays relevant information for standard searches. For searches of tweets "from:user" the sidebar should display info of the user account. Which relevant info can we get from the loklak APIs? Which sidebars can be implemented? Please propose and implement suitable sidebars showing user account information.

![screenshot from 2017-01-11 11-58-39](https://cloud.githubusercontent.com/assets/1583873/21846069/96e080ca-d7f5-11e6-90f4-fb792eb4b04a.png)

**Comment by uttu357** [comment]
Would like to work on this.. :)

**Comment by rishiraj824** [comment]
@uttu357 Are you still working on this? I would like to help.

**Comment by mariobehling** [comment]
@uttu357 Thanks for your interest, but I am unassigning you due to inactivity.

@rishiraj824 Feel free to take it up and make a PR.

**Comment by uttu357** [comment]
@mariobehling I am sorry for the delay... I have a PR in works and will file it soon..

**Comment by uttu357** [comment]
I am using the /api/user.json to retrieve data about the user if the search is a 'from:' type

**Comment by rishiraj824** [comment]
Hey @uttu357, let me know if I can help you in any way.

**Comment by uttu357** [comment]
@rishiraj824 sure.. :+1:
