### ISSUE TITLE
On start page make the background of search limiters light gray

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#204]
The background of the search limiters should be very light gray and have the same color across all the relevant words.

![screenshot from 2017-01-11 12-01-26](https://cloud.githubusercontent.com/assets/1583873/21846165/1d6cdd50-d7f6-11e6-8672-d577c930be48.png)

**Comment by rishiraj824** [comment]
Would like to go ahead with this.

**Comment by hemantjadon** [comment]
I guess this is fixed now
