### ISSUE TITLE
Ensure width of areas stays in relation in different resolutions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#206]
Please compare the Google theme. The areas stay in relation in different resolutions. This is not the case the with the loklak theme. Please help to fix this.

![screenshot from 2017-01-12 04-25-10](https://cloud.githubusercontent.com/assets/1583873/21875900/a5193922-d87f-11e6-83ff-d4b71e642ff4.png)

**Comment by uttu357** [comment]
Fixing this.. :+1:
