### ISSUE TITLE
Implement "Search" and "Search More" using pagination feature and time of tweet

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#212]
The pagination feature was implemented in loklak server on Nov. 6 and for query parameters the SRU 2.0 standard was implemented. See loklak/loklak_server@92f8fe3 i.e.:
first page:
http://loklak.org/api/search.json?timezoneOffset=-60&q=singapore&startRecord=1&maximumRecords=10
second page:
http://loklak.org/api/search.json?timezoneOffset=-60&q=singapore&startRecord=11&maximumRecords=10

Please adapt the "search" and "search more" feature to use the pagination feature to increase the speed.

The question might raise how can we ensure consistency? E.g. result 1-10 are still 1-10 when the user call the second page with the results 11-20 and so forth?

Please use the timestamp of the last tweet - tweet number 10 - on the first page to search for the following 10 tweets and so forth.

**Comment by Achint08** [comment]
Hello @mariobehling can you explain me about the timezoneoffset ?
