### ISSUE TITLE
Implement progressive loading for hashtags at the bottom of search pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#213]
The goal of progressive loading of the hashtags is, that we do not need to load it, if a user never scrolls to this area saving us requests.

**Comment by hemantjadon** [comment]
@mariobehling the hashtags are not loaded in the separate request, they are loaded along with the results from the API and is now that much to computationally heavy task. Are we facing some kind of bottlenecks in certain situations??

**Comment by mariobehling** [comment]
@hemantjadon Yes, you are right. I apparently opened this issue in half-sleep. Closing it. We need to speed up the app. Let's follow up in other issues about this. Cheers.
