### ISSUE TITLE
Avoid hardcoded 404 page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#219]
The 404 pages is hardcoded redirecting to loklak.net. Please implement the 404 page to direct to the current service wherever it is hosted.

**Comment by Achint08** [comment]
I would like to work on this.

**Comment by hemantjadon** [comment]
Hi,
@mariobehling @Achint08 

There are three parts of this issue, or I should say three issues related to routing.

* Showing `404 : Not Found` page incase of wrong route loading. Eg. `http://loklak.net/foobar`

* Giving control to Angular router to control routes. (done using 404.html) [I can explain what is importance of this incase of SPA's] 

* Lazy Loading of Application segments. Like Home and feed are required at load time, but rest (about,contact etc) should be loaded only when required.

**Comment by Achint08** [comment]
@hemantjadon Can you please explain a bit more about the lazy loading thing?

**Comment by sudheesh001** [comment]
@hemantjadon sounds good.

**Comment by Achint08** [comment]
@hemantjadon how will we define path for 404 page in the route?

**Comment by Achint08** [comment]
Hello everyone.This PR must be closed. #225 Fixes this.

**Comment by jig08** [comment]
@Achint08 Thanks.
