### ISSUE TITLE
Ensure clicking on account "name" links to all tweets on loklak search

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#223]
Clicking on names of accounts on loklak.net sends the user to the account page on twitter. Expected: The user should click and see all tweets of this users on loklak.net.

![screenshot from 2017-01-14 16-04-04](https://cloud.githubusercontent.com/assets/1583873/21955843/4523c14a-da73-11e6-80f3-6b3a69608160.png)

**Comment by hemantjadon** [comment]
Using `<a [routerLink]="shard.linkTo" [queryParams]="shard.queryParams">@{{profileName}}</a>`, will fix this.

Someone can take this up :)

**Comment by kaushikgunda** [comment]
I am willing to do this .
