### ISSUE TITLE
Improve design and change fonts

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#226]
Please improve the design as follows:

* [ ] Change all text to use Roboto font, except the word "loklak" should use Courier New (particularly in the logo section)
* [x] On the start page implement the background and font color of loklak as in this image below (but keep "Search" black and change "Search" to Roboto): 
![screenshot from 2017-01-20 01-13-33](https://cloud.githubusercontent.com/assets/1583873/22130733/754e21d2-deae-11e6-9fff-72153a5f6841.png)
* [x] On the bottom bar add "Code" as a bottom menu point in the left (in front) of "Terms" and link it to https://github.com/fossasia/loklak_search

**Comment by hemantjadon** [comment]
@mariobehling Roboto is not a system font, thus using Roboto will increase the load time.
Google itself uses `arial,sans-serif;` to improve the performance, Roboto and arial are quite similar,
 so in my opinion Arial should be used as the font, to increase the speed of the page.

**Comment by rishiraj824** [comment]
@mariobehling I would like to work on these issues.

**Comment by yukiisbored** [comment]
@rishiraj824 Sure, just create a PR with a commit that mentions this issue. Thanks!

**Comment by hemantjadon** [comment]
@yukiisbored @rishiraj824 What do you think about my concern regarding loadtime ?

**Comment by yukiisbored** [comment]
@hemantjadon Well, Google's Font service has caching enabled and it's pretty fast, but I also think it's a good idea to have a fallback font just in case something fails.

**Comment by hemantjadon** [comment]
@yukiisbored I know about the caching, and the speed the caching has Etag of 1day (If i remember correctly), And however fast the service is, its still there to be loaded, and indeed this has impact on load time specially on mobile (have faced this). Also I know the Roboto is great general purpose font, but still it is not used by google. Google uses the `Arial`, Reasons being, It is a system font, there is no flash of unstyled content. and load time is also fast. Another reason being arial and Roboto are quite similar, "Roboto is google's Arial".

I know I am being too concerned about use of webfonts, but what I want is the first page load to be as fast as possible, thus refraining their use.

**Comment by rishiraj824** [comment]
Is this issue yet to be solved?

**Comment by rishiraj824** [comment]
@mariobehling I am adding a PR with the rest of the changes.
