### ISSUE TITLE
Implement Search page theme similar to other services

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#23]
Please implement the result page similar to Google/Twitter.

![screenshot from 2016-10-12 19 02 41](https://cloud.githubusercontent.com/assets/1583873/19320203/97a0aa9e-90b0-11e6-864a-392c8ff723ed.png)

**Comment by mariobehling** [comment]
Please also get rid of the bottom left/right scroll bar.

![screenshot from 2016-10-15 17 04 12](https://cloud.githubusercontent.com/assets/1583873/19411012/788ecb36-92f9-11e6-9266-5e80d2c4e8ba.png)

**Comment by hemantjadon** [comment]
@mariobehling 
I don't know why but there is no horizontal scroll bar on my machine.

And this is bit weird and I am not able to think any reason why it is showing one. Bit surprised there.

What I can do is forcefully hide the overflow-x content. Please suggest ..

**Comment by mariobehling** [comment]
@hemantjadon Please test on different browsers and test with a smaller window size and resolution.

If I make the screen of the Google search smaller it still works as well.

![screenshot from 2016-10-16 00 10 15](https://cloud.githubusercontent.com/assets/1583873/19413699/040d6e66-9335-11e6-8687-7c6f5fff6708.png)

**Comment by hemantjadon** [comment]
@mariobehling
I have tries to fix-up the horizontal scroll issue on the page in #37. It will be great if you can test it again now. Thanks :)

**Comment by mariobehling** [comment]
@hemantjadon Thanks a lot. Looks very good. Cheers!
