### ISSUE TITLE
Editing in front-end of the search page

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/loklak_search#230]
While hovering the cursor over the search bar on loklak.net we get link select cursor; replace it with text select icon. 
![link select](https://cloud.githubusercontent.com/assets/15213246/22174898/1e576fe0-dfea-11e6-8b6f-c4a829aa1d68.png)
![text select](https://cloud.githubusercontent.com/assets/15213246/22174901/2513f7a4-dfea-11e6-9659-ffeaee1b5a53.png)

We even get a text "Please fill in this field." , replace it with "Search here" or "Search"

**Comment by hemantjadon** [comment]
Will you want to work on this??

**Comment by meets2tarun** [comment]
Yes

**Comment by meets2tarun** [comment]
I am searching for the code in src/app/home 
but can't find out .
Please show me a correct way .

**Comment by rishiraj824** [comment]
@mariobehling This issue can be closed now via #258

**Comment by meets2tarun** [comment]
There is one task still left of editing of "Please fill in this field." , replace it with "Search here" or "Search" .
