### ISSUE TITLE
Search service crashes on Clicking 'Show more'

### ISSUE THREAD

**Issue by Achint08** [fossasia/loklak_search#231]
![screen shot 2017-01-22 at 2 00 33 pm](https://cloud.githubusercontent.com/assets/15813932/22181137/2ec2d902-e0ab-11e6-88b0-c2379370cc4f.png)

This error is making Search service to crash. Reason for this is that sometimes apiresponseaggregations is returned as null  on Clicking on "Show more" for new feeds and statistics in info-box is set to undefined which gives an error.

**Comment by mariobehling** [comment]
Ok, not sure, what has been fixed here exactly. A fix would mean that is works I think. It is still not working for me. I have opened another issue here https://github.com/fossasia/loklak_search/issues/272 again.

**Comment by mariobehling** [comment]
![screenshot from 2017-08-16 12-06-29](https://user-images.githubusercontent.com/1583873/29358445-60219fc0-827b-11e7-9b59-214d864c1751.png)

still not working.

**Comment by hemantjadon** [comment]
@mariobehling both the errors in the above screenshot are not due to service crashing on "Show more"  the first error is of service worker not being able to register on load as site is not on `https` second, is due to some image is not found (404) in the cards above.  Both the errors are unrelated to this issue.

**Comment by Achint08** [comment]
@mariobehling Is the application crashing after this?

**Comment by simsausaurabh** [comment]
Already an issue referencing issue with the non availability of results in ```show more```: #272. As per this issue, site doesn't crashes on clicking ```show more```, even there is any results or not.
