### ISSUE TITLE
Show top followers and top followings in search from:user

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#245]
The loklak API enables to get data of followers and following. Please implement this in the sidebar when performing searches "from:user". The goal is to get additional widgets below the existing widget of the top followers and the top following users.

Compare:

http://loklak.org/api.html#user

This servlet provides the retrieval of user followers and the accounts which the user is following. Just submit the screen_name as GET http attribute. Example:

http://loklak.org/api/user.json?screen_name=loklak_app

**Comment by uttu357** [comment]
Would like to work on this :)
