### ISSUE TITLE
Reduce space taken by footer in mobile version

### ISSUE THREAD

**Issue by djmgit** [fossasia/loklak_search#247]
Presently "Apps" , "Code" and  "Terms" ,"Contact" take up new lines in the mobile version. So the entire footer takes up 3 lines with empty spaces in the last two lines. Also the last line ("Terms" ,"Contact") is shifted right and not left-aligned as the previous two lines.

**Comment by rishiraj824** [comment]
Please check this once again @djmgit. I can still see 3 lines for the footer links.
![img_7493](https://cloud.githubusercontent.com/assets/11540785/22598631/17f1ef20-ea5a-11e6-9864-9e654f50da5b.PNG)
