### ISSUE TITLE
Make InfoBox responsive for phones.

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/loklak_search#248]
The InfoBox which one gets while searching using a from:username isn't responsive.
![img_7372](https://cloud.githubusercontent.com/assets/11540785/22399747/22a50f54-e5ca-11e6-95ba-b90f00e447fa.PNG)

**Comment by uttu357** [comment]
Will fix this asap.. :)

**Comment by meets2tarun** [comment]
@rishiraj824 Infobox is also not responsive on pc.
What here mean by responsive ?

**Comment by rishiraj824** [comment]
@meets2tarun The width of the InfoBox should take the whole width of the viewport when on phones. Right now it's aligned to the left.

**Comment by meets2tarun** [comment]
@rishiraj824 don't you think the info box must be at the top followed by the result ?

**Comment by uttu357** [comment]
![wp_ss_20170129_0002](https://cloud.githubusercontent.com/assets/15570642/22509482/333e05f4-e8b4-11e6-806b-1041a96a49f9.png)
@rishiraj824 I am unable to reproduce the issue on my phone. Can you specify the resolution for which you are facing the problem. Thanks.

**Comment by rishiraj824** [comment]
@meets2tarun Yes that would be really good. Feel free to put a PR.

**Comment by meets2tarun** [comment]
@uttu357  i can see the problem on phone having resolution 1920 X 1080.
Whats your phone resolution ?

**Comment by uttu357** [comment]
@meets2tarun Thanks I will see and work on the issue on a phone with a full hd resolution. :+1: Between file a new issue for the info-box being in the top and submit a PR.

**Comment by meets2tarun** [comment]
@uttu357  sure

**Comment by uttu357** [comment]
@rishiraj824 Thanks for your help. The issue could be reproduced when description was missing. Also see #253

**Comment by Achint08** [comment]
Hey everyone. Go ahead and  Test with http://mobiletest.me/ to check for every type of resolutions.

**Comment by meets2tarun** [comment]
@Achint08 Would you please tell to how to make emulator enable to load unsafe script ?

**Comment by Achint08** [comment]
@meets2tarun Just the same way.
Enable load scripts from the shield on right side of the search bar (Google chrome)
And
Disable protection on the left side  (firefox).

**Comment by meets2tarun** [comment]
@Achint08 In the emulator present on mobiletest.me ; it just ask for the URL to display and there is no option to load unsafe script.

**Comment by Achint08** [comment]
![screen shot 2017-02-02 at 10 35 10 pm](https://cloud.githubusercontent.com/assets/15813932/22559690/efd6db8a-e997-11e6-9095-f77ad54362f0.png)

**Comment by meets2tarun** [comment]
Would you please tell how to load unsafe script in chrome Android

**Comment by meets2tarun** [comment]
![screenshot from 2017-02-05 23 51 46](https://cloud.githubusercontent.com/assets/15213246/22626293/248d5db0-ebd0-11e6-9fe1-ef9c26b76bec.png)
@Achint08  It can't be in chrome ...
