### ISSUE TITLE
New searches not always executed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#254]
If the user has performed one search and tries other searches, the searches are not always performed and the page with the new search does not load.

![screenshot from 2017-02-03 11-47-49](https://cloud.githubusercontent.com/assets/1583873/22588613/e84922e6-ea06-11e6-8dec-2d2d82ff29bf.png)

**Comment by Achint08** [comment]
I know about this.
The reason for this is that we were not getting any response from the server for api/user   of your id and some variable is going undefined and search service crashes. The response from server in the image below depicts that.

![screen shot 2017-02-03 at 4 54 50 pm](https://cloud.githubusercontent.com/assets/15813932/22589708/a4a9f9f4-ea31-11e6-9ac5-800c2be97b21.png)

You can check this out if you look at the user-info box  and it will show you empty.

![screen shot 2017-02-03 at 4 58 27 pm](https://cloud.githubusercontent.com/assets/15813932/22589773/04d6b8f8-ea32-11e6-8ad7-e906e5f14a99.png)


For the website , this can be fixed easily.

**Comment by mariobehling** [comment]
This issue still persists in the current page.

![screenshot from 2017-02-11 13-31-15](https://cloud.githubusercontent.com/assets/1583873/22853769/ff635eca-f05e-11e6-9103-118a57a5b2fd.png)

**Comment by Achint08** [comment]
@mariobehling app is crashing due to a minor issue regarding the source of the api. All the reopened will be fixed soon. :)

**Comment by hemantjadon** [comment]
I think new searches are being performed. And this can be closed, please reopen if necessary in future.
