### ISSUE TITLE
Implement a search page for account followers and following

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#256]
The from:account search already offers a sidebar showing the top followers and following. Please implement a page doing the same.

Define a search pattern that needs to be entered into the search bar to find followers of a certain account. What would be the most appropriate?

**Comment by rishiraj824** [comment]
We can filter queries with Followers of '@username'  to get the followers of that user and display them in that page. In that case the feed section would be replaced by the content of this page.

@mariobehling I can give it a shot :)

**Comment by uttu357** [comment]
@mariobehling It can be done using a search pattern such followers:{screen_name}

**Comment by uttu357** [comment]
@mariobehling What all information about the followers and following must be shown on the page?

**Comment by mariobehling** [comment]
> What all information ..

@uttu357 Please start with
* the same info/picture you see on followers pages at Twitter
* ensure the links on the pages work inside loklak
* show number of follower and following
* sort the followers by their own followers count.

**Comment by uttu357** [comment]
Sure will start working on it.. :)
