### ISSUE TITLE
Add tests for circle CI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#26]
Circle CI is already integrated, but tests are lacking.

**Comment by hemantjadon** [comment]
@mariobehling 
The tests are failing on `gh-pages` branch .
There is no requirement of running tests on `gh-pages` as there is only compiled code nothing more, the code which should be tested is on `master` then after passing travis build only it is deployed to `gh-pages`.

**Comment by mariobehling** [comment]
Ok, please delete the unnecessary files on travis. Thank you.

**Comment by hemantjadon** [comment]
> the unnecessary files

I didn't got that ??

**Comment by mariobehling** [comment]
No need to travis,yml etc. in gh-pages branch, if we dont use it at the moment.

**Comment by hemantjadon** [comment]
@mariobehling 
The travis part of the issue can be solved simply by removing `.travis.yml` from the `gh-pages` branch.

While i tried to find such an option for `circle-ci` (build only if circle.yml is present) but there is no such option there. The only option is to blacklist the `gh-pages` using `circle.yml`

So we can do either two things:

* Remove `.travis.yml` and add `circle.yml` adding `gh-pages` to blacklist.

* Or keep both and in both add `gh-pages` to blacklist. ( Remove from safelist)

Please suggest

**Comment by mariobehling** [comment]
Yes, let's remove it.
