### ISSUE TITLE
Add a tweets frequency widget in sidebars for searches

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#260]
Showing the tweet frequency is a useful information. Please add this widget to the sidebar.

![screenshot from 2016-11-03 11 39 30](https://cloud.githubusercontent.com/assets/1583873/19955292/da6bd626-a1ba-11e6-8b7d-8e6b8a0ca564.png)

**Comment by rishiraj824** [comment]
I am willing to work on this feature. Please assign me this.

**Comment by uttu357** [comment]
Duplicate of #188
