### ISSUE TITLE
Home Page not scrolling.

### ISSUE THREAD

**Issue by Achint08** [fossasia/loklak_search#263]
We can't scroll the Home page in landscape mode due to which logo is not shown properly. 

![screen shot 2017-02-07 at 5 58 28 pm](https://cloud.githubusercontent.com/assets/15813932/22691189/379598a6-ed5f-11e6-8e41-c7954ad450d3.png)

**Comment by meets2tarun** [comment]
I would like to work on this

**Comment by Achint08** [comment]
Go ahead @meets2tarun
