### ISSUE TITLE
"Open in Twitter" opens two new tabs

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#266]
The View on Twitter button opens two new tabs. Expected: Should open one tab only.

![screenshot from 2017-02-09 23-15-14](https://cloud.githubusercontent.com/assets/1583873/22805434/c13845b2-ef1d-11e6-86a7-5076eb0f8e4e.png)

**Comment by Achint08** [comment]
Lightbox needs to be worked upon. This is one of the issues going on with lightbox. Otherwise , the UI/UX and design needs to be changed.
