### ISSUE TITLE
Make API request for aggregations.

### ISSUE THREAD

**Issue by Achint08** [fossasia/loklak_search#270]
Currently , we are retrieving data including search results aggregations from all source. To receive aggregations, the data must be retrieved from source being cache. Make a separate request for API aggregations and adjust info-box parameters such that no variable goes undefined.

**Comment by rishiraj824** [comment]
@Achint08 To display the search results on the infobox, I had used the `source=cache`. And yes you are correct that we need to use another query url having `source=all` to get the statuses separately since it is not giving us the Aggregations (Top Twitterers, Mentions, etc.)

**Comment by Achint08** [comment]
@rishiraj824 Will fix this asap. :)
