### ISSUE TITLE
Sidebar not working anymore

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#271]
Please see in screenshot.

![screenshot from 2017-02-11 13-17-52](https://cloud.githubusercontent.com/assets/1583873/22853698/88166552-f05d-11e6-83a1-777dd2a25ca6.png)

**Comment by rishiraj824** [comment]
This issue will be fixed by #270.

**Comment by hemantjadon** [comment]
I guess its working again now 👍  and this can be closed

**Comment by mariobehling** [comment]
@hemantjadon Not working for me on loklak.net. Bottom bar moved to the right now on Chrome.

![screenshot from 2017-02-12 12-29-39](https://cloud.githubusercontent.com/assets/1583873/22861667/fbb83456-f11e-11e6-81f0-fc555290049b.png)
