### ISSUE TITLE
Search bar on start page with gray background on Firefox

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#273]
The search bar on Firefox looks different to Chrome. Please implement it in a white background as well.

![screenshot from 2017-02-11 13-32-44](https://cloud.githubusercontent.com/assets/1583873/22853757/b95c682c-f05e-11e6-98c8-1569a86ad90a.png)

**Comment by rishiraj824** [comment]
Will fix this bug. @mariobehling

**Comment by meets2tarun** [comment]
I can't see the problem.
![screenshot from 2017-02-14 23-11-12](https://cloud.githubusercontent.com/assets/15213246/22941291/f1014672-f30a-11e6-8bbe-decc7f5229c0.png)

**Comment by hemantjadon** [comment]
@mariobehling Not able to reproduce this, can you please give the firfox and OS version?

**Comment by mariobehling** [comment]
Firefox 50.0.2 on Linux Mint

![screenshot from 2017-02-18 14-17-07](https://cloud.githubusercontent.com/assets/1583873/23090936/9fca6eda-f5dc-11e6-81a4-a20f43bbaf05.png)
