### ISSUE TITLE
Before search results are displayed the page "There are no results available" is shown shortly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#276]
On a number of searches, I see, that before search results are displayed the page "There are no results available" is shown shortly. Next the results are displayed.

Expected: There should not be a message "no search results available". Instead it should just display the loading icon.

**Comment by Achint08** [comment]
I would like to work on this. :)

**Comment by hemantjadon** [comment]
Just correct handling of `*ngIf` statement.
