### ISSUE TITLE
Add the voice feature to the search

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#28]
Chrome has the feature to enable voice. Please enable the site to use this feature.

![screenshot from 2016-10-12 20 47 21](https://cloud.githubusercontent.com/assets/1583873/19323430/2cbba41a-90bd-11e6-8068-01772126eed8.png)

**Comment by Achint08** [comment]
@mariobehling @jig08  @hemantjadon I would like to work on this feature.

**Comment by hemantjadon** [comment]
@Achint08 this API is not still cross browser and only available in Chrome so what I think is this can be delayed for now.
