### ISSUE TITLE
Create a screencast showing the main features of the loklak apps

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#282]
Show the loklak project, its components and features in a 3 minute screencast. Include:
1. loklak.org and show the JSON output and highlight sentiment analysis row and Geolocation row and after that the Github repo start page
2. loklak.net and show different searches including the right sidebar widgets and after that the Github Repo start page
3. apps.loklak.org and some cool features of apps (whatever you think is coolest) and after that the github repo.

* Avoid subtitles
* If you cannot fit everything in 3 minutes, check if you can speed up the video (ensure not too fast, so we can still follow).

**Comment by djmgit** [comment]
@mariobehling I would like to work on this :)

**Comment by mariobehling** [comment]
Please go ahead. There is no need to wait for my ok :-)

Try the highest possible resolution, please.

**Comment by djmgit** [comment]
@mariobehling I have made a screencast, I have uploaded it in a separate repo : https://github.com/djmgit/screencast_video

**Comment by mariobehling** [comment]
@djmgit Looks good. Please shorten it a bit and cut it off at 2:36. Thank you.

**Comment by djmgit** [comment]
@mariobehling okay :)

**Comment by mariobehling** [comment]
Another thought: Is it possible to only capture the browser window itself without the browser itself? Only the actual websites?

**Comment by djmgit** [comment]
@mariobehling Please check this  https://github.com/djmgit/screencast_video
I have shortened the video to around 2:36 and shown only the browser window and not the entire browser

**Comment by mariobehling** [comment]
Ok, I see my mistake. Now we dont see the URL anymore and people dont know where they can click. The reason why I was asking to not show the browser is, because the style was not standard and a bit distracting. Maybe we could just have the address bar or a simple browser. Sorry for asking so many changes.

Also, at the end of the video, could you just show for 5 seconds the loklak.org start screen before the video is ending?

**Comment by djmgit** [comment]
@mariobehling So should I include the address bar?

**Comment by mariobehling** [comment]
@mariobehling So should I include the address bar?

yes, please. If possible with a standard browser UI.

**Comment by djmgit** [comment]
@mariobehling cool! I am on it.
Meanwhile could please look into these queries when you get time? 
https://github.com/fossasia/labs.fossasia.org/issues/195

**Comment by djmgit** [comment]
@mariobehling I included the address bar and used a standard browser UI
https://github.com/djmgit/screencast_video

**Comment by jig08** [comment]
@mariobehling @djmgit  I guess we are good to go, closing this.
