### ISSUE TITLE
Website not displaying - Dependency issue?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#284]
The website is not displaying. Please find the reason. Also check dependencies. Some are out of date. Compare: https://gemnasium.com/github.com/fossasia/loklak_search

**Comment by hemantjadon** [comment]
Hi all,
Was going through this issue. Not sure what's happening as I am not near my laptop.
Can someone show me the console when the site is not loading @uttu357 
Dependencies are out of date but I guess it should not be an issue. Build seems fine.

**Comment by rishiraj824** [comment]
Sure @hemantjadon.
 Here you go. It shows ZoneAwareError
![capsxture](https://cloud.githubusercontent.com/assets/11540785/23830220/a65f0e9e-072b-11e7-8824-98e74a0d523d.PNG)

I think what is mentioned in this link is due to the dependency issue of zone.js

**Comment by uttu357** [comment]
@mariobehling Fixed site is back up! :)

**Comment by mariobehling** [comment]
good job!

**Comment by mariobehling** [comment]
So, please check if anyone would like to do a screencast: https://github.com/fossasia/loklak_search/issues/282
