### ISSUE TITLE
Implement autocompletion to suggest search terms

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#29]
The web client prototype (currently at http://loklak.net) has the feature of autocompletion. Please implement autocompletion for the new site.

**Comment by hemantjadon** [comment]
@mariobehling I am thinking of taking this issue next.

I want to know that what will act as a `data-source` for the autocomplete and autosuggest ??

**Comment by mariobehling** [comment]
The server provides this.

@Orbiter Could you give guidance here, please?

**Comment by Orbiter** [comment]
use i.e. suggestions for "oba": http://api.loklak.org/api/suggest.json?orderby=query_count&order=desc&minified=true&q=oba

**Comment by Orbiter** [comment]
There are many options to choose from for the suggestion process, but this one above should be usable for the first shot

**Comment by hemantjadon** [comment]
@Orbiter thanks I'll try and give it a shot.

**Comment by In-vincible** [comment]
I would like to work on this issue.. @hemantjadon should I give a try?

**Comment by hemantjadon** [comment]
@In-vincible 
Sure you can go ahead, i have not made much progress here.
Please share the approach and file structure which you will take.

I would recommend making a `service` that hits `api/suggest.json?q=<query>` and returns an observable. 
Structure `suggest.service.ts` in `shared/services/search/suggest.service.ts`.

If you have a different approach I am happy to listen. 

Cheers :)

**Comment by hemantjadon** [comment]
@In-vincible 
Do setup a test site on gh-pages, and use `angular-cli` for deploying on that, If you face any difficulty in setup i will be happy to help.

**Comment by In-vincible** [comment]
@hemantjadon **" hits api/suggest.json?q=<query> "**  this I didn't get I am supposed to send request to "http://api.loklak.org/api/suggest.json?orderby=query_count&order=desc&minified=true&q=<query>" ,  I just started to explore this project today only :)

**Comment by hemantjadon** [comment]
@In-vincible 
Yes, of course you have to send request to http://api.loklak.org/api/suggest.json?orderby=query_count&order=desc&minified=true&q=

What I was trying to say there is make a separate independent service.

**Comment by jig08** [comment]
@hemantjadon @In-vincible I vouch for `separate independent service for this functionality.`

**Comment by In-vincible** [comment]
@hemantjadon can you give me brief steps for deploying gh-pages using angular-cli

**Comment by hemantjadon** [comment]
@In-vincible Sure.

* The setup is pretty simple just create a fork of this repo.

* Clone the repo to your machine

* Install node>=5 (Use 6) and npm >=3

* Install angular-cli https://github.com/angular/angular-cli#installation

* Then run `ng serve`, if all things went perfectly your server will be running the SPA at http://localhost:4200

* Then you can deploy on gh-pages of your repo simply by `ng github-pages:deploy --message "Optional commit message"`

Refer to https://github.com/angular/angular-cli#deploying-the-app-via-github-pages for exact documentation.

* After this the latest version of your branch will be commited on `gh-pages` branch.
Cheers :)

**Comment by hemantjadon** [comment]
@In-vincible Any updates on this issue ??

**Comment by In-vincible** [comment]
@hemantjadon previously I couldn't start my work as I didn't know angular 2 and was busy with my semester exams, now I have learnt it, I have already setup the local system and read necessary code of the project to start working on my issue, I will publish the gh-pages right away..please accept my apologies for the delay, right now I am writing the service(for autocompletion), will contact you with progress very soon!

**Comment by hemantjadon** [comment]
@In-vincible 
No problems, I just wanted to make sure that you are still working on the task. Take your time.
Make sure that you share the progress here or at gitter.
Cheers :)

**Comment by nikhilrayaprolu** [comment]
@hemantjadon @In-vincible any updates regarding this?
shall I work on this issue?

**Comment by In-vincible** [comment]
@hemantjadon I have written service  /shared/suggest/suggest.service.ts for fetching the suggestions please help me proceed , I think we should show first 6-7 results, should I start writing the UI for auto completion ? Also I had this conflict error in src/app/shared/classes/search/api-response.ts when I pulled as I had the template objects for suggestion in my local, should I clone new copy and copy the suggest service folder?
@nikhilrayaprolu please give me 2-3 days, I will inform you in case I am not able to solve the issue .

**Comment by hemantjadon** [comment]
@In-vincible Well if you have written the service and you are somewhat busy right now you may open up the PR for writing the service, lets first see it.
There are many changes in the core architecture of the code. So your service will not be hooked directly into the component but as a `ngrx/effect`. You can show up the code so that we can discuss what is needed to be done.

If you are busy somehow these days, we can assign this issue to @nikhilrayaprolu and you can take up any issue later.

**Comment by In-vincible** [comment]
I have given the PR with service written only, please suggest changes, busy yeah I will see if am not able to devote time I will assign it to @nikhilrayaprolu :)

**Comment by Achint08** [comment]
@mariobehling I want to work on this. Can I ?

**Comment by uttu357** [comment]
This issue can be closed after #250
