### ISSUE TITLE
ng serve giving: "You have to be inside an angular-cli project in order to use the serve command."

### ISSUE THREAD

**Issue by vimarshc** [fossasia/loklak_search#291]
The documentation is a little confusing for me. 

First I installed angular-cli, which gave the the following message: 
```

npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/ng -> /usr/local/lib/node_modules/angular-cli/bin/ng
/usr/local/lib
└─┬ angular-cli@1.0.0-beta.28.3 
  └── UNMET PEER DEPENDENCY rxjs@^5.0.1

npm WARN @angular/core@2.4.10 requires a peer of rxjs@^5.0.1 but none was installed.

```

After this I cloned the repository, I did cd into loklak_search and ran 
`npm install. 
`
After which I tried running 

`
$ ng serve 
`

which gave me the following error: 
`
You have to be inside an angular-cli project in order to use the serve command.
`

But there is a .angular-cli.json in the directory. 
I have upgraded npm, node. I'm not sure what I'm doing wrong. 

I wanted to inquire if the README is outdated and I should be installing @angular/cli.

**Comment by uttu357** [comment]
Sorry for the problem! The dependencies were recently updated and I forgot to update the line in the readme. Yes you have to install @angular/cli. I'll update the README asap.

**Comment by vimarshc** [comment]
The "Installation" and "How to Deploy" seem a little confusing to me, may I submit a pull-request with an updated README?

**Comment by uttu357** [comment]
@vimarshc I have already changed it to @angular/cli in #292 as i stated before but if you think there is some other problem to submit a PR! :)
