### ISSUE TITLE
Have single requests for Search and Aggregations

### ISSUE THREAD

**Issue by rishiraj824** [fossasia/loklak_search#293]
Now that using `source=all` parameter in the query gives us the aggregations, we can have one single reducer and only one query request for getting both the aggregations and the tweets. 

[http://api.loklak.org/api/search.json?q=fossasia&source=all](http://api.loklak.org/api/search.json?q=fossasia&source=all)

**Comment by uttu357** [comment]
Yeah this would be reduce the no. of requests and will also solve issue #287. What do you think @hemantjadon @mariobehling ?

**Comment by hemantjadon** [comment]
@uttu357  this was implemented earlier but was not successful as many times aggregations object was not returned from the server or something like that. @Achint08  can you tell the exact reason.

**Comment by Achint08** [comment]
@hemantjadon Hello Me and @rishiraj824 met @Orbiter at the Summit. We requested him to implement it this way so he did. :)
