### ISSUE TITLE
Show more is still displayed after showing all of the followers.

### ISSUE THREAD

**Issue by Achint08** [fossasia/loklak_search#296]
Show more is expected to hide after all the followers are displayed. But it is still displayed.

**Comment by daminisatya** [comment]
Provide a screenshot

**Comment by Achint08** [comment]
This is the [link](http://loklak.net/search?query=followers:Achintsharma08) if you search for my followers on loklak search because we don't have to scroll much in that case(coz I don't have many).
After all followers are displayed , Show more is still displayed.
