### ISSUE TITLE
Followers SEARCH not working properly

### ISSUE THREAD

**Issue by Achint08** [fossasia/loklak_search#297]
Sometimes , We are receiving data from the server side for `followers:user` but still it is not displayed.
Data from the server
![screen shot 2017-03-21 at 3 43 00 pm](https://cloud.githubusercontent.com/assets/15813932/24142969/3327e426-0e4e-11e7-8086-bef63f3486b3.png) .

Results not being displayed
![screen shot 2017-03-21 at 3 43 22 pm](https://cloud.githubusercontent.com/assets/15813932/24142980/3cf5b3f2-0e4e-11e7-9505-b98247e822d7.png)

**Comment by uttu357** [comment]
Can you show an example when this happens? I am unable to recreate the issue!

**Comment by Achint08** [comment]
Hey @uttu357 . I came across this when I searched for `followers:mariobehling` 2-3 times.

**Comment by uttu357** [comment]
Thanks! I will try to recreate the issue and find the problem.

**Comment by Achint08** [comment]
@uttu357 I was working on it already. But you can work on it if you want to. :)

**Comment by uttu357** [comment]
As currently i am not able to create the issue! Please go ahead and solve it asap.. :)

**Comment by hemantjadon** [comment]
This is no longer relevent as followers search and followeres UI has been removed.
