### ISSUE TITLE
Create sub pages with different filters

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#3]
The screenshot below shows different facettes/filters.

![screenshot from 2016-10-15 15 44 05](https://cloud.githubusercontent.com/assets/1583873/19410497/58e46170-92ee-11e6-9e44-a1f26f325235.png)

Please implement it in the same style for
- [ ] All https://github.com/fossasia/loklak_search/issues/17
- [ ] Video Results https://github.com/fossasia/loklak_search/issues/49
- [ ] Image Results https://github.com/fossasia/loklak_search/issues/48
- [ ] News Results https://github.com/fossasia/loklak_search/issues/46

**Comment by FleetAdmiral** [comment]
I'd like to take this up! Anyone that could extend upon what is exactly expected over here?

**Comment by mariobehling** [comment]
@FleetAdmiral Still interested? Please go ahead if you like. I also updated the description.

**Comment by FleetAdmiral** [comment]
@mariobehling Yea, i'll take it up. Thank you!

**Comment by mariobehling** [comment]
@FleetAdmiral How is it going? Any questions?

**Comment by FleetAdmiral** [comment]
@mariobehling I'm currently preoccupied with my mid terms which get over on the 19th. I'll have to put off this work till then. I hope thats fine? 
P.S: Thanks for checking up on me!

**Comment by mariobehling** [comment]
@FleetAdmiral No problem. I unassign this, so someone else can take it up. There are enough issues to take up or if this is not solve just do it later. Cheers.

**Comment by hemantjadon** [comment]
@mariobehling would it be nice to show the video and images (in the cards along with the results) in the `all` tab and then just filter those in `different tabs` essentially keeping the design same?

**Comment by mariobehling** [comment]
@hemantjadon Yes, images and videos should be shown and currently are not displayed.

Then in the tabs for the start we simply show tweets with images or videos.

![screenshot from 2016-10-17 20 06 52](https://cloud.githubusercontent.com/assets/1583873/19449328/6ce8bf64-94a5-11e6-8a9d-39304aad7e1f.png)

**Comment by hemantjadon** [comment]
@mariobehling @Orbiter 
There is a certain issue which I am facing right now regarding the the images in individual posts

* The api gives the image url in the `images` key of the  as `https://pic.twitter.com/{id}`

* Now on visiting this link redirects us to a url `https://twitter.com/{user_name}/status/{post_id}/photos/{photo_number}`. (an html response)

* Thus this link cannot be directly used with the `<img src="...">`. (expected image response)

* The actual image is located at a url like `https://pbs.twimg.com/media/{id}`, (taken from actual twitter feed)

* Please suggest a method how the image can be obtained from the url of the `api` or any other method which will work.

**Comment by hemantjadon** [comment]
Something i found on a twitter forum
https://twittercommunity.com/t/how-do-i-extract-the-url-to-the-photo-i-just-tweeted/7165/3

* This is related to twitter api but i think it might point towards the right path.

**Comment by Orbiter** [comment]
I will have a look at the back-end

**Comment by hemantjadon** [comment]
@Orbiter 
Sir any progress regarding this on backend?
