### ISSUE TITLE
Start page loading slowly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#305]
The start page of http://loklak.net should be loading pretty quickly as there is not much on it. Please check why it loads slowly and fix this.

**Comment by uttu357** [comment]
The js and css files are not being minified and optimized after build is done.. Will alter the deploy script and do the changes asap..

**Comment by rishiraj824** [comment]
![screenshot 79](https://cloud.githubusercontent.com/assets/11540785/24521107/8dc5e02a-15a8-11e7-82f1-0a4d98ec4d76.png)

The vendor file which is built while in production is of a huge size. After going through some issues I found these links. Maybe we need to go through the files which are being bundled by webpack and minimize the polyfills and removed the unused files.

- [1](https://github.com/AngularClass/NG6-starter/issues/143)
- [2](https://github.com/reactjs/redux/issues/809)
- [3](https://github.com/angular/angular-cli/issues/4059)

**Comment by hemantjadon** [comment]
@rishiraj824 the vendor files are angular specific what we can do right now is enable the prod mode in in CLI and see how the size is reduced.
