### ISSUE TITLE
Refreshing search results in missing data on tweet frequency chart

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#307]
The tweet frequency chart does not show any information after a result page is refreshed.

![screenshot from 2017-03-30 14-04-57](https://cloud.githubusercontent.com/assets/1583873/24516662/e038f844-1551-11e7-9ba9-bc5fccd284d9.png)

**Comment by hemantjadon** [comment]
This is working as expected, please reopen if necessary.
