### ISSUE TITLE
Sidebar missing content

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#324]
![screenshot from 2017-04-13 10-13-03](https://cloud.githubusercontent.com/assets/1583873/24996092/e98719ec-2007-11e7-8b8c-f59548cc19d9.png)

**Comment by rishiraj824** [comment]
This issue can be referenced at #322.

**Comment by rishiraj824** [comment]
@mariobehling @hemantjadon I think this can be closed now via #326
