### ISSUE TITLE
loklak.net shows "no results" while loklak.org shows plenty of JSON results

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#328]
Trying a number of searches we often get no results event though loklak.org shows a JSON output.

**Comment by hemantjadon** [comment]
@mariobehling Can you provide a test case for this? Because sometimes what happens is the server doesn't respond immediately and thus timeout errors are thrown. maybe thats the case. We would need more information regarding this and why this behaviour is happening.

**Comment by mariobehling** [comment]
@hemantjadon We also need developers who use the app actively and test it through. Try out 10 searches using the same tab. What is your experience?

**Comment by hemantjadon** [comment]
This issue is also regarding the inconsistent response sent by the server.
The loklak search is working displaying the error message only if there are no results returned by the server.
