### ISSUE TITLE
Add RSS feed and link to JSON output to all searches

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#33]
Please add a link for RSS and JSON for search results on right below top bar.

**Comment by hemantjadon** [comment]
@mariobehling 
Is a link to raw JSON (which was used to construct results) and raw RSS is expected ??

**Comment by mariobehling** [comment]
Would be good to have like Google and Twitter used to offer this.

**Comment by hemantjadon** [comment]
@mariobehling 
I am not able to understand this. Can you please elaborate ... please provide the links if any :)

**Comment by hemantjadon** [comment]
@mariobehling 
Please provide some more information regarding this issue. :)

**Comment by mariobehling** [comment]
We will go into detail here later. Delay for now.

**Comment by uttu357** [comment]
@mariobehling Would like to work on this. Can you provide some information regarding the issue. :)

**Comment by mariobehling** [comment]
Currently api.loklak.org provides the option to get an RSS feed. We just want to reroute this feed through the service we provide here.

![screenshot from 2017-02-04 12-19-27](https://cloud.githubusercontent.com/assets/1583873/22618077/448d4e38-ead4-11e6-8127-2c732ae40ef3.png)

**Comment by mariobehling** [comment]
A simple raw link through two buttons a) Green JSON Button and b) Orange RSS Button as below is sufficient.

Please use this button for example and create a similar button for the JSON download.
![rss-40674_960_720](https://user-images.githubusercontent.com/1583873/29972967-352363fc-8f2e-11e7-81a7-f591dd6c6e87.png)
https://pixabay.com/de/rss-nachrichten-futtermittel-blog-40674/

![screenshot from 2017-09-01 15-57-31](https://user-images.githubusercontent.com/1583873/29973179-e3fd2340-8f2e-11e7-82f1-6d1b48e8a2f1.png)

**Comment by anshumanv** [comment]
I'll work on this.

**Comment by ParthS007** [comment]
I am working on it due to inactivity 👍
