### ISSUE TITLE
Show message of search of last 30 days

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#330]
The loklak server now only shows messages of the last 30 days.

Please display a message in the search screen accordingly:

"Searching social media messages of the last 30 days."

![screenshot from 2017-04-29 14-59-09](https://cloud.githubusercontent.com/assets/1583873/25555720/383c13f6-2cee-11e7-885a-0b08e4449065.png)

**Comment by Achint08** [comment]
I would like to work on it. :)
