### ISSUE TITLE
Enhance "no result" page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#331]
Please enhance the "no result" page as follows.

* Change text as follows:
"Your search ... did not match any results within the last 30 days."

* Align search text on left and right to the search bar (just like the search results).

![screenshot from 2017-04-29 15-13-58](https://cloud.githubusercontent.com/assets/1583873/25555759/0ff90f4c-2cef-11e7-978d-3530a6f4c5c4.png)

**Comment by shaz13** [comment]
I have a fix, pushing a PR @hemantjadon. Kindly review
