### ISSUE TITLE
loklak.net shows less results than loklak.org

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#332]
Please perform multiple searches and compare them to loklak.org.

Todays seach of "fossasia" shows 4 results on loklak.net and dozens of results on loklak.org.

Investigate the issue and fix it.

**Comment by hemantjadon** [comment]
Loklak search is displaying all the results sent by the server. Sometimes, server sends the varied amount of results for the same query, which might be the case here. Please reopen if necessary.
