### ISSUE TITLE
Footer navigation bar does not appear correctly on safari

### ISSUE THREAD

**Issue by isuruAb** [fossasia/loklak_search#336]
navigation bar does not show correctly in safari browser.

It shows like this.
<img width="1232" alt="screen shot 2017-05-01 at 10 43 06 am" src="https://cloud.githubusercontent.com/assets/7692626/25572693/551f8c6e-2e5b-11e7-8c4f-bcc425c01107.png">

**Comment by Achint08** [comment]
@isuruAb You can work on it if you want to. :)
