### ISSUE TITLE
Suggested search queries can not be selected by arrow key

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/loklak_search#337]
While searching on 'http://loklak.net/search', the suggested search queries can not be selected by down array key.

![image](https://cloud.githubusercontent.com/assets/10573038/25741465/95a469da-31a8-11e7-8650-bd465626072b.png)

I would like work on this issue.

**Comment by Achint08** [comment]
You can work on it. :)

**Comment by Achint08** [comment]
@hemantjadon  Can be closed

**Comment by hemantjadon** [comment]
Yes this can be closed after #362
