### ISSUE TITLE
Pressing Down Arrow Key shows autocomplete of some other browser form history

### ISSUE THREAD

**Issue by AnupKumarPanwar** [fossasia/loklak_search#338]
On Pressing 'Down Arrow Key'  in search box, autocomplete of some other browser form history  is shown.

![image](https://cloud.githubusercontent.com/assets/10573038/25741577/f7f368a2-31a8-11e7-8d02-a84740269062.png)

I Would be glad to fix this issue

**Comment by Achint08** [comment]
@AnupKumarPanwar Just make autocomplete off for the input and submit your PR.

**Comment by Achint08** [comment]
Can be closed!
