### ISSUE TITLE
Add reStructuredText Markup for document generation

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/loklak_search#339]
The flow of documentation generation is changing. As @yukiisbored mentioned in a comment in https://github.com/loklak/loklak_server/pull/1127 and I quote 

> Actually, I'm planning to push the raw rST/md files to the repository and let it build it via CI rather than pushing the compiled HTML pages so everything would be integrated nicely in Sphinx. Due to time constraints (mainly because of School), I'm currently finding a good way to push it nicely to the master branch of the repository and combining the index files into one.

From my understanding it will require creating a README.rst file in all the repositories.

**Comment by Achint08** [comment]
Can be closed now!
