### ISSUE TITLE
Adapt height of top bar and simplify search box

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#34]
![screenshot from 2016-10-15 15 48 53](https://cloud.githubusercontent.com/assets/1583873/19410524/046e5208-92ef-11e6-8ead-a1422d4a3e27.png)

* [x] Please implement the same height as the Google search bar.
* [x] Currently the search gets a blue kind of shadow, when it is highlighted. Please only change the line color to blue and do not show a box shadow.

**Comment by hemantjadon** [comment]
@jig08
I have tried and match the heights within 1px. PR #36

**Comment by mariobehling** [comment]
Cannot confirm this as solved. Please compare.

![screenshot from 2016-10-15 23 57 26](https://cloud.githubusercontent.com/assets/1583873/19413644/6cf25f92-9333-11e6-8e1a-85019d2c2f46.png)

Please also test on different browsers.

![screenshot from 2016-10-15 23 58 40](https://cloud.githubusercontent.com/assets/1583873/19413646/76c69614-9333-11e6-8f0c-b127738fe80d.png)

**Comment by mariobehling** [comment]
Good job!
