### ISSUE TITLE
Responsiveness triggers sooner than expected and meta text below the search is not responsive

### ISSUE THREAD

**Issue by shaz13** [fossasia/loklak_search#350]
**Pics:** 
Try resizing the chrome window width wise and observe that search bar shrinks sooner even though the place is available. 

![screenshot from 2017-05-09 22-06-12](https://cloud.githubusercontent.com/assets/24438869/25861954/f62db956-3503-11e7-93b7-a5bf33829c58.png)

Text under search cuts to the edge of the page.
![screenshot from 2017-05-09 22-06-43](https://cloud.githubusercontent.com/assets/24438869/25861981/0f16b940-3504-11e7-84cc-ab719f19451a.png)

**Comment by Achint08** [comment]
@shaz13 Sure. Proceed with it. :)

**Comment by Achint08** [comment]
Closed via #371.

**Comment by shaz13** [comment]
Thanks @Achint08 for pointing it. Closing now.
