### ISSUE TITLE
Improve Lightbox

### ISSUE THREAD

**Issue by Achint08** [fossasia/loklak_search#353]
- [ ] Make Lightbox responsive.

- [ ] Make light box accumulate media elements in it.

**Comment by shaz13** [comment]
Hi @Achint08 , 
Could I take up the issue?  Also, a screenshot of lightbox might be helpful. ( I am assuming it's a search result tweets container) Thanks!

**Comment by Achint08** [comment]
Hey @shaz13 Sure. You can work on the responsiveness of the lightbox . This is the lightbox 
![screen shot 2017-05-10 at 1 58 36 pm](https://cloud.githubusercontent.com/assets/15813932/25889827/d5e7de6c-3588-11e7-8e66-eda8bef915a8.png)

**Comment by hemantjadon** [comment]
Closing this as lightbox has been removed from the UI.
