### ISSUE TITLE
Codecov unknown

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#354]
Please fix the Codecov coverage.

**Comment by hemantjadon** [comment]
https://codecov.io/gh/fossasia/loklak_search/settings

Here it says:

> GitHub Integration is installed. However, this repository is not enabled.
> > [Click here to your installation listings](https://github.com/organizations/fossasia/settings/installations/21410)
> > * Find Repository access and add loklak_search to the list.
> > * May take a couple minutes for our system to get notices of new projects added.

Someone with proper repository access rights will have to enable the codecov for the project.
