### ISSUE TITLE
Problem with deployment after upgrade

### ISSUE THREAD

**Issue by Achint08** [fossasia/loklak_search#356]
Local deployment not working after upgrade.

**Error given**
`Unhandled Promise rejection: can't convert undefined to object ; Zone: <root> ; Task: Promise.then ; Value: TypeError: can't convert undefined to object` .

**Comment by hemantjadon** [comment]
@Achint08 where is this bug coming ? When I tested locally it worked fine? Is this coming on deployment on ghpages

**Comment by Achint08** [comment]
@hemantjadon Problem exists with local deployment.
