### ISSUE TITLE
from:<user> search not showing proper results

### ISSUE THREAD

**Issue by singhpratyush** [fossasia/loklak_search#358]
Example: http://loklak.net/search?query=from%3AGoogle.

This happens because the frontend encodes `%` to `%25`, resulting in a search for `q=from%253AGoogle`.

**Comment by Achint08** [comment]
Hey @singhpratyush . Where are the results not proper? Kindly reproduce a bit.

**Comment by singhpratyush** [comment]
@Achint08: If you go to the link I mentioned in the description, you will see something like this - 
![screenshot from 2017-05-15 15-09-01](https://cloud.githubusercontent.com/assets/10860278/26051700/93a1cf6c-3980-11e7-9795-2f2435a2ad75.png)

This doesn't contain Tweets from `@Google`, but it is a result of searching `from` and `Google` with some characters between them.

If you take a look at the request that is sent to the server, the query is `from%253AGoogle`, while it should be `from%3AGoogle`. This problem is arising because the query is being URL encoded twice - 
`from:Google` -> `from%3AGoogle` -> `from%253AGoogle`.

Hope this helps.
