### ISSUE TITLE
Feed info box takes too long to load for from:<user> search

### ISSUE THREAD

**Issue by singhpratyush** [fossasia/loklak_search#359]
The user info box in the right corner takes too long to load.

Example - http://loklak.net/search?query=from%3AGoogle. It fetches ~188KB data before displaying it.

This happens because the frontend searches for http://api.loklak.org/api/user.json?screen_name=Google&followers=1000&following=1000, which returns failry large amount of JSON.

**Comment by Achint08** [comment]
Thanks for opening this issue. 
@hemantjadon I think to increase speed of various components of our web app, we should now think to make api service configurable.

**Comment by singhpratyush** [comment]
In this case, a simple solution would be to reduce the number of followers and following that is being requested.

**Comment by Achint08** [comment]
@singhpratyush We have a followers page which gives us information about the followers of the user. So currently, to show more followers we have made the default number of requested followers 1000. We will have to compensate there in that case. Rather, we can make api service configurable.

**Comment by singhpratyush** [comment]
I understand that scenario, but for the search page, the number can be limited. We only need to show 12 in each field. We may go with requesting more in the `followers:<user>` search type.

**Comment by hemantjadon** [comment]
@singhpratyush yeah bulk of data is getting wasted as the application doesn't require all the set at once. Will work on reducing the data.
Also the Service configuration is also a good idea but it will require careful implementation as sometimes configuration leads to redundancy in code.
