### ISSUE TITLE
Missing profile picture for various accounts in loklak search

### ISSUE THREAD

**Issue by singhpratyush** [fossasia/loklak_search#360]
Example - http://loklak.net/search?query=from%3Asinghpratyush_

![screenshot from 2017-05-15 14-35-57](https://cloud.githubusercontent.com/assets/10860278/26050370/003e6db0-397c-11e7-95e3-715aeca4ab51.png)

This is (probably) because of changing profile picture of people while loklak holds the URL for older picture.

**Comment by Achint08** [comment]
@singhpratyush Kindly check the server side for this issue. As such, I will go through the front end side if there is some problem existing.
