### ISSUE TITLE
Videos and Images tab shows result for empty query.

### ISSUE THREAD

**Issue by kavithaenair** [fossasia/loklak_search#361]
Issue: Bug Report

Even after clearing the search bar , the videos and images tab shows result.

![screenshot 67](https://cloud.githubusercontent.com/assets/18421291/26098929/df759dc6-3a46-11e7-9290-a106f1abb4ea.png)

![screenshot 68](https://cloud.githubusercontent.com/assets/18421291/26098934/e4515876-3a46-11e7-82ae-8784dbeca797.png)

**Comment by Achint08** [comment]
@hemantjadon This issue can be closed. But have to be kept in mind while implementing media sub tabs.
