### ISSUE TITLE
Make auto-complete box fixed

### ISSUE THREAD

**Issue by Achint08** [fossasia/loklak_search#375]
The auto-complete box is moving with the scroll.

![screen shot 2017-06-01 at 3 58 31 pm](https://cloud.githubusercontent.com/assets/15813932/26753047/7d755a42-487b-11e7-80cc-4620cbd79f81.png)

Make autocomplete-box fixed.

**Comment by hemantjadon** [comment]
This is the WIP in @angular/material itself (#4093)[https://github.com/angular/material2/issues/4093]

We will keep an eye on this issue and get it fixed

**Comment by simsausaurabh** [comment]
@mariobehling The suggestion box seems to be fixed now, after project's Angular update. This issue could be closed.
