### ISSUE TITLE
.m3u8 formats of videos

### ISSUE THREAD

**Issue by Achint08** [fossasia/loklak_search#404]
Videos from Api Response are sometimes in format of [.m3u8](https://en.wikipedia.org/wiki/M3U) files. Question is how to aggregate these parts of videos and display it in one frame?

**Comment by singhpratyush** [comment]
@Achint08: That should no longer be the case.

The server was once in a state that it fetched `m3u8` videos but after https://github.com/loklak/loklak_server/pull/1206 getting merged, all the links fetched `mp4`, `youtube.com...` or `vimeo.com...`.

**Comment by Achint08** [comment]
@singhpratyush 
Check this out
http://api.loklak.org/api/search.json?timezoneOffset=-330&q=barcelona&filter=video.

**Comment by singhpratyush** [comment]
You can skip the `.m3u8` videos there. There will always be more links to the video in there. The `m3u8` file will be pointing the same videos only - 
```sh
$ http https://video.twimg.com/ext_tw_video/875628649487007744/pu/pl/IGwUa0wHs12FVXOR.m3u8
HTTP/1.1 200 OK
...

#EXTM3U
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=256000,RESOLUTION=240x240,CODECS="mp4a.40.2,avc1.420015"
/ext_tw_video/875628649487007744/pu/pl/240x240/sVtQFq3y9iCSVIpK.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=832000,RESOLUTION=480x480,CODECS="mp4a.40.2,avc1.42001f"
/ext_tw_video/875628649487007744/pu/pl/480x480/t-AgvFHWALfm1uX6.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1280000,RESOLUTION=720x720,CODECS="mp4a.40.2,avc1.4d0020"
/ext_tw_video/875628649487007744/pu/pl/720x720/kHl6Lfkhzzh5AqtX.m3u8
```

These `m3u8`s will result in videos in `.ts` format - 
```sh
$ http https://video.twimg.com/ext_tw_video/875628649487007744/pu/pl/720x720/kHl6Lfkhzzh5AqtX.m3u8
HTTP/1.1 200 OK
...

#EXTM3U
#EXT-X-VERSION:6
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:3
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-ALLOW-CACHE:YES
#EXTINF:3.000,
/ext_tw_video/875628649487007744/pu/vid/0/3000/720x720/IPuhm5F_YFQlUNJr.ts
#EXTINF:3.000,
/ext_tw_video/875628649487007744/pu/vid/3000/6000/720x720/7jGYXWbbBjuA4pLV.ts
#EXTINF:3.000,
/ext_tw_video/875628649487007744/pu/vid/6000/9000/720x720/5KDfhR5P_Rj5vEGd.ts
#EXTINF:3.000,
/ext_tw_video/875628649487007744/pu/vid/9000/12000/720x720/bPwY-QzGxqNiaayZ.ts
#EXTINF:3.000,
/ext_tw_video/875628649487007744/pu/vid/12000/15000/720x720/vl8psjWGofAjViMi.ts
#EXTINF:3.000,
/ext_tw_video/875628649487007744/pu/vid/15000/18000/720x720/rpHHZ_1DkjdJ-Wmv.ts
#EXTINF:3.000,
/ext_tw_video/875628649487007744/pu/vid/18000/21000/720x720/FSGhIgavL7r9mY7U.ts
#EXTINF:2.717,
/ext_tw_video/875628649487007744/pu/vid/21000/23717/720x720/35C8fYeX-66nPskx.ts
#EXT-X-ENDLIST
```

These `.ts` files are partitioned by time (better streaming).

I don't know if there is some package that plays `.m3u8` files directly.

**Comment by hemantjadon** [comment]
@Achint08 let's skip `.m3u8` for now, I know the details of it, but it is too complex to implement correctly at this state of the application. This can be the feature, which we can user after everything is done.
