### ISSUE TITLE
Making Advanced search Navbar of feed results

### ISSUE THREAD

**Issue by Achint08** [fossasia/loklak_search#418]
Idea is to make advanced search navbar of feed results just like market leader (without hard coding). Moreover, adding options/filters and linking to different actions.

**Comment by hemantjadon** [comment]
Not able to understand here? What are you trying to suggest, some mocks and screenshots will be nice.

**Comment by Achint08** [comment]
@hemantjadon I was talking about the advanced search nav bar.
![screen shot 2017-06-22 at 3 06 00 pm](https://user-images.githubusercontent.com/15813932/27427399-77df7302-575c-11e7-9480-595673c023ee.png)

**Comment by hemantjadon** [comment]
@Achint08 This seems decent, but first we need to have the searches for these working then only it make sense for this :)

**Comment by Achint08** [comment]
@hemantjadon I wanted to do this because every time you have to change css to add new advanced search option. Like I did for `Views`. I just want to make it simple to add.
It will be just a prototype. Will comment it out for the time being. As soon as you get up with customizable search, we can use that.

**Comment by Achint08** [comment]
@hemantjadon Can I proceed with this now?

**Comment by hemantjadon** [comment]
Yeah sure go ahead 👍
