### ISSUE TITLE
Show related hashtags on bottom of search result page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#42]
On the bottom of search page results we often find "related searches". Please implement a similar thing "related hashtags".

![screenshot from 2016-10-17 17 18 12](https://cloud.githubusercontent.com/assets/1583873/19443727/f5ba4f0a-948d-11e6-9f57-8b49e6ee1e43.png)

**Comment by hemantjadon** [comment]
@mariobehling 
Do we want the hashtags related to the search term here ??

**Comment by mariobehling** [comment]
> Do we want the hashtags related to the search term here ??

Either related to the search term or related to the tweets of the search output, e.g. show hashtags that appear in the search results.

@Orbiter: How can we get this from API?

**Comment by mariobehling** [comment]
Here is an example link to get results of a search: http://api.loklak.org/api/search.json?q=usa%20since:2016-10-16%20until:2016-11-01&source=cache&count=0&fields=hashtags&limit=6

{
  "readme_0": "THIS JSON IS THE RESULT OF YOUR SEARCH QUERY - THERE IS NO WEB PAGE WHICH SHOWS THE RESULT!",
  "readme_1": "loklak.org is the framework for a message search system, not the portal, read: http://loklak.org/about.html#notasearchportal",
  "readme_2": "This is supposed to be the back-end of a search portal. For the api, see http://loklak.org/api.html",
  "readme_3": "Parameters q=(query), source=(cache|backend|twitter|all), callback=p for jsonp, maximumRecords=(message count), minified=(true|false)",
  "search_metadata": {
    "itemsPerPage": "0",
    "count": "0",
    "count_twitter_all": 0,
    "count_twitter_new": 0,
    "count_backend": 0,
    "count_cache": 3079,
    "hits": 3079,
    "period": 9223372036854775807,
    "query": "usa since:2016-10-16 until:2016-11-01",
    "client": "78.53.39.70",
    "time": 5451,
    "servicereduction": "false",
    "index": "messages"
  },
  "statuses": [],
  "aggregations": {"hashtags": {
    "usa": 839,
    "job": 279,
    "jobs": 174,
    "hiring": 170,
    "jobsearch": 67,
    "america": 57
  }}
}

**Comment by mariobehling** [comment]
Please implement this with a time interval "since" and show the results of the last 2 weeks.

If there are no results of the last two weeks, do not show "related hashtags" widget.

**Comment by uttu357** [comment]
Hi! @mariobehling can I work on this issue?

**Comment by uttu357** [comment]
Thanks! @mariobehling I am thinking of showing hashtags that appear in the search results.. They are present for every feed result at this route. http://api.loklak.org/api/search.json?q=fossasia

**Comment by hemantjadon** [comment]
@uttu357 This will be nice start :)
Accumulate all the hashtags used in all the results along with frequencies and then show them in sorted order at the bottom.

Use ES6 syntax if possible :)

**Comment by uttu357** [comment]
Sure! :+1:

**Comment by hemantjadon** [comment]
This issue is fixed for a start in the above PR #127.  Now what we can work on this issue is making the `hashtags` as sort of redux state. That is with each element when it arrives we also save the 
The hashtags also which come with it.

What do you think @uttu357 ?

**Comment by uttu357** [comment]
Making hashtags as sort of redux state is necessary and helpful when multiple components need them as is the case with the API Results and Query. If such a use case arises then we can move it and save it as a redux state?

Your thoughts? @hemantjadon

**Comment by hemantjadon** [comment]
Well yeah right now there is only this component making use of the hashtags. 
But this seems like the application component is keeping a slice of the data (computed from the state) and making a sort of personal state. Which should not be the case with a presentational component. Also it seems very likely that this hashtag data might be used by some other component.
We can maybe delay this for now, but eventually the state needs to move to store. So we can make a call here do it now or let the need arise and then do it later.

All opinions are welcomed :)

**Comment by uttu357** [comment]
Then yeah let us do it now as it is very likely that it might be used by some other component. Ill file a PR asap. :+1:

**Comment by hemantjadon** [comment]
@uttu357 Sure :) Cheers :)
