### ISSUE TITLE
Suggestions staying even when search result is already being displayed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#439]
Please only show suggestions during typing. Compare it to Google, please.
![screenshot from 2017-07-06 03-40-23](https://user-images.githubusercontent.com/1583873/27891955-321e0936-61fd-11e7-9366-8f78b951aa41.png)

**Comment by mariobehling** [comment]
Still not solved.

**Comment by singhpratyush** [comment]
@mariobehling: It seems fixed for me. Have you tried a hard refresh (`CTRL+F5`).

**Comment by hemantjadon** [comment]
@mariobehling I fixed this in above PR, can you please check again

**Comment by simsausaurabh** [comment]
Duplicate of #549 and seems to be fixed now.
