### ISSUE TITLE
Enhance front page image and add favicon

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#44]
- [ ] The front page image is currently 64KB. Please check how this image size can be decreased without loosing quality.
- [ ] Currently there is no favicon defined. Please add the loklak animal as a favicon.

**Comment by sharkness** [comment]
I can complete this. 
Would you prefer just the browser favicon.ico or would you like the apple, ms, and android favicons, as well?

**Comment by mariobehling** [comment]
@sharkness Anything that is relevant for this project. Not sure, if it needs Android favicon for example as this repo caters for the browser. Thank you.

**Comment by mariobehling** [comment]
There was a favicon added, but it was not linked apparently and does not show up in the browser tab.

**Comment by hemantjadon** [comment]
@mariobehling 
This is due to the fact angular-cli generates the build.

Only the stuff in `assets` folder is emitted as is, so there is a need to place and link favicon from `assets` folder.
