### ISSUE TITLE
Script for test deploy

### ISSUE THREAD

**Issue by hemantjadon** [fossasia/loklak_search#446]
* The current script for the test deployment is `slow` and uses `angular-cli-ghpages`.

* The main reason for this is the fact that this uses `cloning` the whole repository. Which makes is extremely slow especially on unreliable connections (This step may take about half an hour on slow network)

* What I propose here is to have A new script (maybe NPM or maybe bash) to make this process faster by using `commit and push` instead of cloning

* We can then also enable the features like the Per branch separate deployment, which will be useful.

**Comment by vibhcool** [comment]
You may write python `pygit2` script for `git` tasks

**Comment by hemantjadon** [comment]
@vibhcool I am hesitant to create another project dependency by introducing python in the project.
