### ISSUE TITLE
Activate search bar with cursor on opening start page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#45]
When a user enters a search site like google.com, the site activates the search bar and shows the cursor in the bar right away. This means the user does not have to click the search box to type.

Please implement it in the same way.

![screenshot from 2016-10-17 17 37 44](https://cloud.githubusercontent.com/assets/1583873/19444415/a95655b6-9490-11e6-9d0e-fcba7324491d.png)

**Comment by sahil865gupta** [comment]
autofocus on the input field will fix it.
