### ISSUE TITLE
Add meta data info to pages

### ISSUE THREAD

**Issue by hemantjadon** [fossasia/loklak_search#455]
**Parent Issue #311**

* Add metadata info to the pages for Search engines to be able to easily crawl the page

**Comment by mariobehling** [comment]
The start page still does not have a "title".

* Please add a title to each page using the search term
* Add the <title>Peer to Peer Social Media Message Search Engine</title> to the front page
* Re-add the image alt tag "Distributed Social Media Message Search Engine" to the loklak logo on the front page

**Comment by hemantjadon** [comment]
@mariobehling The start page has a title Loklak Search. The titles should be small IMO, so title "Loklak Search" is good IMO

We can have the description tag to contain this 
> Peer to Peer Social Media Message Search Engine

**Comment by mariobehling** [comment]
@hemantjadon There is no rule that titles should be two words only. I cannot believe how much discussion such a small issue requires. Please follow up and resolve this issue entirely.
