### ISSUE TITLE
Implement news sub tab with results from news organizations

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#46]
Many news organizations have a twitter and youtube account. Please show a stream from news organization in the sub tab "News".

Implement as follows:
-  [ ] Create a json file with a list of accounts of social media of news organizations (sort alphabetically and by media, e.g. Twitter, Youtube)
-  [ ] Show the stream just like other search results in a sub tab "News"

![screenshot from 2016-10-17 17 44 10](https://cloud.githubusercontent.com/assets/1583873/19444626/7b49f60e-9491-11e6-8542-d2f840f77b7d.png)

**Comment by yasirunilan** [comment]
Can I work on this ?

**Comment by mariobehling** [comment]
@yasirunilan Sure, go ahead after you solve the other issues you claimed. But lets also understand our best practices: Please only claim one issue at a time. Thank you.

**Comment by yasirunilan** [comment]
Sure, For the moment I will not be working on this. in the other issues

**Comment by Achint08** [comment]
@mariobehling Can I work on this?

**Comment by uttu357** [comment]
@mariobehling Can you elaborate more on this? The json file should be created manually? If no then how should we find a way to scrape the news organizations twitter account from somewhere? I think that we need to find a way to regularly update and find news organizations twitter accounts.. any suggestions? @hemantjadon?

**Comment by Achint08** [comment]
@mariobehling If anyone else wants to work on issue, he/she can do that. I am working on some other issue right now. :)
