### ISSUE TITLE
Auto-refreshing mode for media walls

### ISSUE THREAD

**Issue by Achint08** [fossasia/loklak_search#460]
The idea is to 

- [ ] Sent request to the loklak server after 10 seconds for new feeds and getting an auto-refreshing mode for media walls.

- [ ] Adding animations to add and display new feeds to media wall in an appealing way.

**Comment by Achint08** [comment]
@mariobehling  @hemantjadon  Please provide your suggestions?

**Comment by hemantjadon** [comment]
Okay let's try this 👍
