### ISSUE TITLE
Create subtabs for image results

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#48]
The screenshot below shows different facettes/filters.

![screenshot from 2016-10-15 15 44 05](https://cloud.githubusercontent.com/assets/1583873/19410497/58e46170-92ee-11e6-9e44-a1f26f325235.png)

Please implement it in the same style for Image Results

Subissue to https://github.com/fossasia/loklak_search/issues/3

**Comment by AbhishekSharma102** [comment]
@mariobehling hey, i'd like to take this up. Could you please elaborate?

**Comment by mariobehling** [comment]
The idea is to get subtabs on the service, same as on twitter for example.

**Comment by AbhishekSharma102** [comment]
okay, please assign this to me. Thanks

**Comment by mariobehling** [comment]
@AbhishekSharma102 I have sent you an invite to FOSSASIA. Please join the org. GitHub only allows assignments for members of an org. Cheers.

**Comment by hemantjadon** [comment]
Can be closed this is fixed now
