### ISSUE TITLE
Subtab for video results

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#49]
The screenshot below shows different facettes/filters.

![screenshot from 2016-10-15 15 44 05](https://cloud.githubusercontent.com/assets/1583873/19410497/58e46170-92ee-11e6-9e44-a1f26f325235.png)

Please implement it in the same style for video results.

Subissue to #3

**Comment by rishiraj824** [comment]
@mariobehling How are we detecting videos, images etc. ? Is it available in the API?

**Comment by hemantjadon** [comment]
@rishiraj824 
We are not currently detecting the videos. but it can be done pretty easily using `videos` key from the `api-response`.
This issue can be solved when we get correct URL'S check #3 for further details.

**Comment by rishiraj824** [comment]
Alright. Then the sub tabs are on hold till #3 is fixed, I guess.

**Comment by hemantjadon** [comment]
Well I have created the UI part of the tabs but I am waiting for the backend code to be rectified.

**Comment by rishiraj824** [comment]
@hemantjadon was just going to ask you if that was made. Awesome then !

**Comment by hemantjadon** [comment]
This has been implemented thus can be closed
