### ISSUE TITLE
Some Chinese characters not showing up correctly on suggestion

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#491]
![screenshot from 2017-07-25 11-24-50](https://user-images.githubusercontent.com/1583873/28565367-561b12b4-712c-11e7-8128-d73f1769f90f.png)

The suggestions show that some Chinese characters are not rendered correctly.

**Comment by Achint08** [comment]
@mariobehling This is how it is received from the backend. I have opened issue for the same on server side. https://github.com/loklak/loklak_server/issues/1360 .
Screenshot for the same.
![screen shot 2017-07-25 at 3 08 52 pm](https://user-images.githubusercontent.com/15813932/28565958-6257a6a4-714b-11e7-9136-0c3c7df3d9ba.png)
