### ISSUE TITLE
Migrate Site to https

### ISSUE THREAD

**Issue by hemantjadon** [fossasia/loklak_search#534]
The loklak.org page, should be migrated to `https`, There are two options for this.

* Use default github pages domain.

* Use 3rd party proxy like cloudfare for the setup.

The Cloudfare setup will require the [registeration](https://www.cloudflare.com/) on the site 

* First creation of account on cloudfare, then site registeration

* Then we will need to update the `nameservers`, from domain manager, to the cloudfare nameservers, and this should make the shift from requests to cloudfare servers, thus making the the requests go over `https`

**Comment by ParthS007** [comment]
@hemantjadon I want to work on it. I have registered the site on cloud fare.

**Comment by AnshulMalik** [comment]
Isn't loklak.org already serving over https?

**Comment by simsausaurabh** [comment]
@hemantjadon this will require to change the nameservers from where the actual website has been hosted(domain manager), and only an admin can do it.
