### ISSUE TITLE
Hashtags "##" are showing up twice and cursor not acting as expected

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#536]
![screenshot from 2017-08-14 20-30-53](https://user-images.githubusercontent.com/1583873/29285799-0b6a6ef4-8130-11e7-8298-cc4f60b59f05.png)

* Hashtags on a number of areas are showing up twice
* When user goes with the cursor over the result page the cursor does not act as it is supposed to be. Also copying with left side mouse click is not acting as normal

**Comment by dilantha111** [comment]
Hi I have this same issue multiple times. Does someone already working on it ? If not can I start working on it ?

**Comment by simsausaurabh** [comment]
@mariobehling @singhpratyush I don't see this is a problem anymore, can it be closed?

**Comment by simsausaurabh** [comment]
@mariobehling @singhpratyush this problem has been solved in the new trending hashtags section. This issue can be closed now :+1:
