### ISSUE TITLE
Search bar suggestions slowly closing after user hit enter

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#544]
The whole UI feels slow. One issue is, that after the user enters a search term and hits "enter", the top search bar closes very slowly.

![screenshot from 2017-08-16 11-59-52](https://user-images.githubusercontent.com/1583873/29358274-bb074990-827a-11e7-89b9-2cf927706a93.png)

**Comment by dilantha111** [comment]
Hi @mariobehling  can I work on this ?

**Comment by simsausaurabh** [comment]
@mariobehling is this still an issue? Now the suggestion box is closing on enter and not lagging. Or this issue references some more bugs?
