### ISSUE TITLE
Startpage Hashtags are shortened

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#545]
Hashtags should not be shortened. The area should just be expanded.

![screenshot from 2017-08-16 12-24-49](https://user-images.githubusercontent.com/1583873/29359212-01e1b082-827e-11e7-9eb2-f979c9c24e34.png)

**Comment by mish24** [comment]
Can I take this up?

**Comment by Achint08** [comment]
Please procced @mish24.

**Comment by mish24** [comment]
@mariobehling This can be closed

**Comment by dilantha111** [comment]
Hi @mariobehling  is this still open ? If so can you explain a bit more ?
