### ISSUE TITLE
Different font sizes and styles in same area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#547]
Font sizes and alignment in the secondary menu below the search box should be following one implementation similar to Google.

Expected:
![screenshot from 2017-08-16 12-41-50](https://user-images.githubusercontent.com/1583873/29359803-65f5545a-8280-11e7-8f3b-bfb4ae1adb50.png)

Current Implementation:
![screenshot from 2017-08-16 12-41-22](https://user-images.githubusercontent.com/1583873/29359812-6fbd5a64-8280-11e7-9cd4-f116b107d5a2.png)

**Comment by mish24** [comment]
@mariobehling If no one is working on this I would like to take this up

**Comment by yasirunilan** [comment]
I would work on this issue

**Comment by ParthS007** [comment]
working on this :+1:

**Comment by ParthS007** [comment]
@mariobehling Please close this issue. Thanks :+1:

**Comment by simsausaurabh** [comment]
@mariobehling This issue can be closed :+1:
