### ISSUE TITLE
Search bar suggestions not closing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#549]
![screenshot from 2017-08-17 12-48-43](https://user-images.githubusercontent.com/1583873/29408950-7beb71a2-834a-11e7-9029-8780c3f28b01.png)

If the user enters a search term on the no result page and the search is performed and the user clicks again. At whatever stage this happens, the search bar does not close the suggestions

**Comment by mish24** [comment]
Can I take this up?

**Comment by AnshulMalik** [comment]
Definitely @mish24

**Comment by ansh-ptel** [comment]
can I work on this?

**Comment by Redarcher9** [comment]
is this bug resolved? can I still work on this?

**Comment by vyaspranjal33** [comment]
@AnshulMalik  it seems this bug has been resolved

![image](https://user-images.githubusercontent.com/11768143/35183937-18608d8a-fe14-11e7-8121-38630237533d.png)
