### ISSUE TITLE
Add "Privacy" Page and link it in Footer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#554]
We need a page for a privacy policy. Use the same style as for "Terms" page. Also do the following:
* Add link "Privacy" in the footer on the right hand side
* Implement the following order: Privacy, Terms, Contact

![screenshot from 2017-08-19 16-45-58](https://user-images.githubusercontent.com/1583873/29487685-e74b104c-84fd-11e7-9749-03b0904a4e06.png)

**Comment by hemantjadon** [comment]
@mariobehling What all we need to add on this privacy page?

**Comment by ParthS007** [comment]
@mariobehling i want to work on issue , please tell what exactly need to be added in privacy page?
