### ISSUE TITLE
Search Icon Wrongly Placed

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/loklak_search#573]
When we search for a query which has no result, then the search icon seems to be wrongly placed.
![loklak](https://user-images.githubusercontent.com/15213246/30390185-d44d6b96-98d2-11e7-8434-f043c89c46a2.png)

**Comment by GingerDragon7** [comment]
Seems like that issue is resolved.....that it's coming fine!!!
![screenshot from 2017-09-15 20-58-03](https://user-images.githubusercontent.com/17198965/30490797-b1066d36-9a58-11e7-9e84-8f8ebdc698e5.png)

**Comment by meets2tarun** [comment]
yes, you are correct.The issue only persists in firefox

**Comment by yasirunilan** [comment]
I tested on Firefox 55.0.2 (64-bit). This issue is not there.

**Comment by Achint08** [comment]
Hey @meets2tarun . Does this issue still persists?

**Comment by meets2tarun** [comment]
@Achint08 Yes
I'm on Firefox Nightly v56

**Comment by yasirunilan** [comment]
Issue prevails 
![screenshot from 2017-10-10 15-39-05](https://user-images.githubusercontent.com/9814784/31381119-3afb4cc4-add1-11e7-9224-f447725dce94.png)
Firefox 56.0

**Comment by ParthS007** [comment]
@mariobehling Please close this issue.
