### ISSUE TITLE
Can't make multiple search actions over multiple tabs

### ISSUE THREAD

**Issue by MrMathur** [fossasia/loklak_search#579]
Having submitted one search on one tab, the search keyword remains the same across all tabs. Hence you cannot make multiple search actions over multiple tabs.

I'm new to open source contribution, and am willing to work on this issue. Any help/approach to solving the problem is appreciated.

**Comment by 0x48piraj** [comment]
I think, you have figured out the problem, but because of being new in **Github**, you're kinda struck!


> This may help : https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by simsausaurabh** [comment]
@MrMathur Could you please provide more information on this issue? I am able to do multiple searches on multiple browser tabs. Being on different tabs of loklak on same browser tab you can make search too, It is possible.
