### ISSUE TITLE
loklak.org not providing search results

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#581]
https://api.loklak.org is providing results while loklak.org does not.

**Comment by VaibhavVishal07** [comment]
This is what https://api.loklak.org is showing.
![untitled](https://user-images.githubusercontent.com/31325525/32146465-e7c04550-bcfd-11e7-82ad-5226701e1fc2.png)

**Comment by harshit98** [comment]
One of the reason can be the loading of HTTP content over HTTPS. I would like to look at this issue. 👍

**Comment by harshit98** [comment]
@mariobehling This issue can be closed now. It has been fixed in #593.
