### ISSUE TITLE
Translations needed for JSON definition list of all repos and filemasks, so they can be imported to weblate

### ISSUE THREAD

**Issue by ParthS007** [fossasia/loklak_search#582]
[https://github.com/fossasia/labs.fossasia.org/issues/231](https://github.com/fossasia/labs.fossasia.org/issues/231)

Please refer to this issue for more info.

**Comment by simsausaurabh** [comment]
@ParthS007 What is the update on this? Is it required?

**Comment by ParthS007** [comment]
No, closing this :+1:
