### ISSUE TITLE
No search results.

### ISSUE THREAD

**Issue by VaibhavVishal07** [fossasia/loklak_search#584]
The website loklak.org is not providing any results.
![untitled](https://user-images.githubusercontent.com/31325525/32146445-a02fb02c-bcfd-11e7-9c96-71f88ce96f03.png)

**Comment by harshit98** [comment]
Similar to #581

@mariobehling Please close this issue.

**Comment by ParthS007** [comment]
@VaibhavVishal07 Please close the issue.
