### ISSUE TITLE
Search box displays search button wrongly on Firefox

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#588]
Please see issue below:
![screenshot from 2017-11-08 17-22-58](https://user-images.githubusercontent.com/1583873/32560353-b50e1c5a-c4a9-11e7-897e-3a96ac23e789.png)

**Comment by ParthS007** [comment]
I want to work on it

**Comment by singhpratyush** [comment]
@ParthS007: Please proceed. Thanks.

**Comment by ParthS007** [comment]
Now working on this

**Comment by ParthS007** [comment]
@mariobehling Please close this issue.
