### ISSUE TITLE
Error in importing modules from @angular

### ISSUE THREAD

**Issue by ParthS007** [fossasia/loklak_search#590]
There are many modules which are not imported while running loklak_search on the local machine. This is due to improvements in angular version and certain modules are not supported now. For example, MaterialModule was removed as of `2.0.beta-11` and Deprecation of "md" prefix. Please go through the [changelog](https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes).
Here are screenshots of the issue.
![1](https://user-images.githubusercontent.com/24358501/32575447-0eb2128e-c4fa-11e7-8bf8-bab9fe9c01f1.png)
![2](https://user-images.githubusercontent.com/24358501/32575449-11340bc0-c4fa-11e7-9182-b86ff75e19f8.png)
![3](https://user-images.githubusercontent.com/24358501/32575452-1312726a-c4fa-11e7-8415-8b3d6e9bbab6.png)

Now we have to update all files accordingly for proper functioning .

**Comment by ParthS007** [comment]
@mariobehling  @hemantjadon  @Achint08 . Your views

**Comment by mariobehling** [comment]
Yes, please go ahead. Cheers.
