### ISSUE TITLE
Type and 404 Error in Console while searching 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/loklak_search#597]
![capture](https://user-images.githubusercontent.com/24358501/32740498-27cb966e-c8c9-11e7-80c0-67de237df5b9.PNG)

**Comment by ParthS007** [comment]
I am working on this issue .

**Comment by harshit98** [comment]
@ParthS007 Provide the steps to reproduce the bug.

**Comment by starlord1311** [comment]
i would like to work on this. can i? @ParthS007

**Comment by harshit98** [comment]
Is it still showing errors @ParthS007 ? Please provide the steps to reproduce the bug.

**Comment by ParthS007** [comment]
It is not showing errors at present so closing this
