### ISSUE TITLE
Improvements in the UI of suggestion box.

### ISSUE THREAD

**Issue by harshit98** [fossasia/loklak_search#601]
- Currently, the UI of suggestion box looks like this:
![screen shot 2017-11-15 at 8 38 57 am](https://user-images.githubusercontent.com/22245418/32816889-015546e2-c9e1-11e7-8506-976074130bcd.png)
It should be equal to the width of the search bar.

- On pressing 'enter' key, the autocomplete box should close. Currently, it is not happening. The user has to wait for it until results are loaded.

**Comment by ajayns** [comment]
I'd like to check out this issue and maybe come up with a fix.

**Comment by ParthS007** [comment]
Ok. @ajayns . Please go ahead 👍
