### ISSUE TITLE
Adding more icon links in the top right dropdown menu

### ISSUE THREAD

**Issue by marvin08** [fossasia/loklak_search#603]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current Behaviour:**
Currently, the top right dropdown menu only contains the icon links of the major FOSSASIA projects. 

**Expected Behaviour:**
There should be more icon links like bug report, contact, code etc. in the dropdown menu.

**Screenshots of the issue:**
(Not applicable here)

**Would you like to work on this issue?**
Yes.

**Comment by marvin08** [comment]
Suggestions required @mariobehling @hemantjadon @Achint08.

**Comment by ParthS007** [comment]
@marvin08  We already have code, contact links in Footer. I don't think we will need this in the service box.

**Comment by marvin08** [comment]
@ParthS007 I know but it will only make the service box look better from the user's point of view if we add icon links of bug report etc.

**Comment by mariobehling** [comment]
Please follow the way https://susper.com does it.

**Comment by marvin08** [comment]
Ok @mariobehling

**Comment by sudwebd** [comment]
@mariobehling I can do the necessary changes , tell me which images to use for the icons..

**Comment by marvin08** [comment]
@sudwebd I am done with this issue but faced some problem while deploying loklak_search, which I will resolve soon as currently I am having exams in my institute. Hope you understand.

**Comment by sudwebd** [comment]
@marvin08 my PR has passed the checks

**Comment by marvin08** [comment]
Taking this up as it is not solved till now. :+1:
