### ISSUE TITLE
Disable the browser autocomplete feature.

### ISSUE THREAD

**Issue by harshit98** [fossasia/loklak_search#604]
**Current Behaviour**

Whenever a search action is done, the browser autocomplete appears. It shows search terms which have been searched in the past.

**Expected Behaviour**

Disable the browser autocomplete feature.

**Screenshots of the bug**

![screen shot 2017-11-18 at 6 36 18 pm](https://user-images.githubusercontent.com/22245418/32984173-579cb614-ccc7-11e7-82a8-978b6ad663e9.png)

**Comment by ParthS007** [comment]
claiming this

**Comment by ParthS007** [comment]
@harshit98 Now it is working fine, Please close this issue 👍
