### ISSUE TITLE
Adding LICENSE file to loklak_search repository

### ISSUE THREAD

**Issue by marvin08** [fossasia/loklak_search#609]
**Current behavior:**
Currently, loklak_search repository is not having any license.

**Expected behavior:**
License file should be added to loklak_search repository.

**Screenshots of the issue:**
(Not applicable here)

**Comment by harshit98** [comment]
@marvin08 Kindly, let's make this issue as a GCI task. :)

**Comment by marvin08** [comment]
ok @harshit98.

**Comment by marvin08** [comment]
@harshit98 @hemantjadon @Achint08 Please add GCI label to this issue.
