### ISSUE TITLE
Implement contact page (rename imprint)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#61]
Instead of imprint please add a contact page at `/contact`.

Use the same design as the "about" page and add the following information:

Contact Us

Loklak
93 Mau Than Street
Can Tho
Viet Nam
Phone +84 (0) 907 65 29 27
Email: support@loklak.net
Board of Directors: Phuc Hau Dang
Loklak Ltd.  is registered in Can Tho, Viet Nam.   

Report a safety or abuse issue affecting our products.
If you know of a safety or abuse problem with any of loklak's services, we'd like to hear about it right away. Please use our contact form to report the issue.

**Comment by rishiraj824** [comment]
on it @mariobehling. Please assign me this.

**Comment by jig08** [comment]
@rishiraj824 Joined the FOSSASIA Codeheat team ?

**Comment by mariobehling** [comment]
@rishiraj824 Hi, any updates?

**Comment by pranayyelugam** [comment]
Is this issue fixed ? . If not, I would like to do this.

**Comment by mariobehling** [comment]
@pranayyelugam Sounds great. There is already a pull request regarding this issue here: https://github.com/fossasia/loklak_search/pull/66 Any feedback?

@rishiraj824 Are you stuck here? Maybe @pranayyelugam can help?

**Comment by rishiraj824** [comment]
No it'll be done by today.  Sorry for the delay.

**Comment by hemantjadon** [comment]
@rishiraj824 If there is any problem regarding the workflow or tests please ask, :)

**Comment by pranayyelugam** [comment]
It seems that @rishiraj824  has it under control .

**Comment by mariobehling** [comment]
This issue is not finished yet. The link to "imprint" on bottom of pages is still there and has not been changed. Instead of imprint please add a contact page at /contact. Also change "Google" to "loklak" please.

@rishiraj824 Please see if you would like to finish this issue.

Or @pranayyelugam feel free to make a PR for this small change. Cheers.

**Comment by mariobehling** [comment]
Also, please leave some space before the bottom gray bar.

![screenshot from 2016-10-27 09 48 38](https://cloud.githubusercontent.com/assets/1583873/19776846/97123f72-9c2a-11e6-8103-b890987869d4.png)

**Comment by rishiraj824** [comment]
@mariobehling updated the commit. Check for the changes.
