### ISSUE TITLE
Auto deployment using Surge 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/loklak_search#610]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Presently, Contributor has to manually deploy on Heroku and provide a deployment link.

**Expected behavior:**
After auto-deployment, It will be easy for reviewers to review PR as deployment link is generated automatically.

**I am working on this Issue**

**Comment by harshit98** [comment]
@ParthS007 Please let this issue be a GCI task. :)

**Comment by ParthS007** [comment]
working on it :+1:
