### ISSUE TITLE
Dockerize loklak_search

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/loklak_search#613]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

Containerize the `loklak_search` with docker
**Screenshots of the issue:**

**Comment by hemantjadon** [comment]
What will be the use of doing this? What purpose will the docker image serve?

**Comment by bhaveshAn** [comment]
@hemantjadon For Docker, There would be another way to install Loklak_search and it will be virtual one, which is quite excited though.

**Comment by apargarg** [comment]
@hemantjadon I guess it can help work developers in the same environment, since earlier when I was working on loklak_search there were errors pertaining to different versions of angular/cli and material.
