### ISSUE TITLE
Change PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/loklak_search#615]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Presently, there is no checklist of `Best practices , upto date declaration with master branch and doc provide` so we need these.
**Expected behavior:**
To add this checklist of `Best practices , upto date declaration with master branch and doc provide`

![screenshot from 2017-11-28 00-58-00](https://user-images.githubusercontent.com/22936570/33285188-8e93c376-d3d7-11e7-9a1e-ffc75c5d4d1a.png)
**Screenshots of the issue:**

**Comment by AnshulMalik** [comment]
Please provide some more info on the issue :)
