### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by ArmenGabrielyan16** [fossasia/loklak_search#619]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

These two items are kind of a must for open source projects. So I think it will be great to add License and Code of Conduct to Loklak Search. I would like to work on this issue.
**Screenshots of the issue:**

**Comment by ParthS007** [comment]
@ArmenGabrielyan16  This is already in GCI task.

**Comment by ArmenGabrielyan16** [comment]
@ParthS007 OK. I see there is already an Issue about License, but I can't find anything Code of Conduct. Could you please correct me if I am wrong?

**Comment by mariobehling** [comment]
This is a software application. There is not need for a CoC.
