### ISSUE TITLE
Multiple presses of view button shows multiple dropdowns

### ISSUE THREAD

**Issue by apargarg** [fossasia/loklak_search#620]
There is a possible bug wherein the views button on multiple presses creates multiple dropdowns instead of toggling the drop down. I would like to work on this issue. Can I ?
Same issue with Tools' buttons i.e. Any Time and Any country
![screenshot from 2017-12-05 21-05-00](https://user-images.githubusercontent.com/10288194/33615369-00796cc4-da00-11e7-942b-ba7e636c9afe.png)

**Comment by hemantjadon** [comment]
Yes @apargarg You can work on it, see if Angular Material has any relevant bug opened in this regard.

**Comment by apargarg** [comment]
Ya sure @hemantjadon .

**Comment by apargarg** [comment]
The problem arises when the API isn't working. It is toggling perfectly in case of the successful data retrieval. Please close the issue.

**Comment by apargarg** [comment]
The problem arises when the API isn't  working. It is working fine with perfect toggle when the data is successfully retrieved.

**Comment by hemantjadon** [comment]
Thanks for this information @apargarg.
