### ISSUE TITLE
Videos Taken from Twitter Aren't Visible in Search

### ISSUE THREAD

**Issue by flaredragon** [fossasia/loklak_search#624]
**I'm submitting a ...**
- [x] bug report
- [x] feature request

**Current behavior:**
- Only the Tweet Which Have Video Are Been shown without any video
- <b>There is No link to reach the Tweet Only Link to Profile is Active</b>

**Expected behavior:**
- The Videos could be displayed on the search portal itself.
- The Link For the tweet should be there.

**Screenshots of the issue:**

![screenshot from 2017-12-13 17-23-56](https://user-images.githubusercontent.com/29121452/33937946-7cc0d3a4-e02b-11e7-85b9-a2120bac3e05.png)

I Want To work on this issue

**Comment by ParthS007** [comment]
@flaredragon I am not able to reproduce this issue when I run it on localhost.Please see this 
![image](https://user-images.githubusercontent.com/24358501/34020723-cb5082ea-e15b-11e7-8f5b-2bbd8912b879.png)

**Comment by flaredragon** [comment]
Umm I found the problem the links scraped are served over http protocol while loklak search on https blocks it.

**Comment by flaredragon** [comment]
And yes the tweets are non clickable like if I want to see a tweet directly on twitter there is no link present.(I think this feature should be there on a search engine)

**Comment by Cam-B** [comment]
Yes. there absolutely should be a link. Interesting to see this works on localhost. what do we need to do to make it work with https though?

**Comment by Cam-B** [comment]
Browsed to http://loklak.org/search?query=cats and now I can see the videos on my desktop.
On Firefox android no luck yet.

**Comment by simsausaurabh** [comment]
@mariobehling @singhpratyush This issue can be closed, since the vidoes are already served on https only and the issue could be the outcome of slow internet speed. The videos are not being blocked.

The videos are served on ```https``` only:

![screenshot from 2018-06-17 14-00-43](https://user-images.githubusercontent.com/16608864/41506198-f887e480-7236-11e8-8f33-154596a87678.png)

**Comment by flaredragon** [comment]
@simsausaurabh I was talking about the videos which are coming from Twitter. Youtube Ones are served perfectly fine this wasn't an issue of slow internet speed.Youtube Videos are being embed according to the code but the ones directly from Twitter are blocked due to Cross Origin Blocking
