### ISSUE TITLE
UI for Infobox needs to be updated

### ISSUE THREAD

**Issue by ajayns** [fossasia/loklak_search#628]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

**Expected behavior:**

A neater UI than random words placed in a box

**Screenshots of the issue:**

![image](https://user-images.githubusercontent.com/20743219/34390264-b11bd9f2-eb64-11e7-8590-ce7e75206c1d.png)

**Comment by Ploypiti** [comment]
@ajayns Hi, are you working on this, if not can I claim the issue?

**Comment by ajayns** [comment]
@Ploypiti Hey! Yes I'm currently working on this and was actually waiting for inputs from the mentors before finalizing a PR
