### ISSUE TITLE
Add Surge deployed PR link to PR template

### ISSUE THREAD

**Issue by ParthS007** [fossasia/loklak_search#630]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Presently, PR is deployed but the link is present in Travis logs

**Expected behavior:**
Contributor has to fill the only PR number after updating the PR template.

**GCI Students are free to claim this**
 Refer to this if you face any problem - fossasia/susper.com#852

**Comment by abishekvashok** [comment]
Can I work on this?

**Comment by 0x48piraj** [comment]
@ParthS007 I can do this !

**Comment by singhpratyush** [comment]
@abishekvashok: Please proceed with this.

@0x48piraj: There are many other pending issues that you may be interested in. Please take a look.

**Comment by abishekvashok** [comment]
@singhpratyush sorry for the delay on it...

**Comment by abishekvashok** [comment]
Done in #633
