### ISSUE TITLE
9-dot navigation menu to other apps not closing

### ISSUE THREAD

**Issue by simsausaurabh** [fossasia/loklak_search#632]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

The 9-dot menu (navigation to fossasia apps) at top-right side is not closing when the mouse is clicked anywhere else on the page, except at the 9-dot icon itself.

**Expected behavior:**

The opened menu should automatically get close when the mouse is clicked anywhere on the page.

**Screenshots of the issue:**

![screenshot from 2018-01-04 18-20-18](https://user-images.githubusercontent.com/16608864/34564317-32186bca-f17c-11e7-9cfa-463d3326d89b.png)
![screenshot from 2018-01-04 18-20-37](https://user-images.githubusercontent.com/16608864/34564319-364bcf84-f17c-11e7-91a0-6f9fc1e9d820.png)

**Comment by simsausaurabh** [comment]
I'm working on this issue, any suggestion would be helpful.

**Comment by ParthS007** [comment]
@simsausaurabh  Please update your status and let us know if you face any difficulty 👍

**Comment by jajodiaraghav** [comment]
No update has been made for past 2 weeks. Can I take this one up?

**Comment by simsausaurabh** [comment]
@ParthS007 @jajodiaraghav I am working on it and I'll make PR for the same soon.

**Comment by rupav** [comment]
@simsausaurabh what is the update on this issue? @jajodiaraghav are you taking this up if no update comes up?
