### ISSUE TITLE
Clicking outside the Menu in Header should close it

### ISSUE THREAD

**Issue by jajodiaraghav** [fossasia/loklak_search#638]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Right now to close the Menu, one needs to click on the link again.

**Expected behavior:**
Clicking anywhere outside it, should close it.

**Comment by jajodiaraghav** [comment]
Claiming this issue

**Comment by singhpratyush** [comment]
Is this duplicate of https://github.com/fossasia/loklak_search/issues/632?

**Comment by ParthS007** [comment]
yes @singhpratyush , It is a duplicate of #632

**Comment by jajodiaraghav** [comment]
@singhpratyush Yes, you are right. I didn't see it.
The title "9-dot navigation menu to other apps not closing" sounds dubious to me

**Comment by jajodiaraghav** [comment]
No update has been made on #632 for the past 18 days.
@singhpratyush @ParthS007 Can I claim this?

**Comment by simsausaurabh** [comment]
@singhpratyush this issue can be closed, since it's already been solved.
