### ISSUE TITLE
Structuring of application

### ISSUE THREAD

**Issue by hemantjadon** [fossasia/loklak_search#64]
Will it be good to have the `model/schema` (Typescript classes) of the `api-responses` or just plain JSON should be used?

* Using classes will make the use of the response object more **robust** and easier to write.

* But using plain JSON gives us more flexibility in case structure of response changes over time.

Please Suggest :)

**Comment by mariobehling** [comment]
I tend to using Typescript classes. 

The structure of responses will be extended over time, but I think we could handle this.

But, I don't have a well-funded opinion. What is your personal preference?

**Comment by hemantjadon** [comment]
@mariobehling
In my opinion I think it's nice to have typed structure it gives us a good type checking in texteditor and more structured codebase in general.

**Comment by mariobehling** [comment]
@hemantjadon Ok, let's proceed that way then.
