### ISSUE TITLE
Service menu and Search Box overlaps in devices with smaller screen size.

### ISSUE THREAD

**Issue by praveenojha33** [fossasia/loklak_search#646]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Top right service menu containing links to different Fossasia services overlaps with search icon on changing screen size. 

**Expected behavior:**
It should be properly oriented.

**Screenshots of the issue:**
![mistake](https://user-images.githubusercontent.com/25537606/35526374-34d9e714-054d-11e8-88ad-eb4144302aa2.png)
![error](https://user-images.githubusercontent.com/25537606/35777732-e8e1d6f6-09d8-11e8-98c3-7d53c8b310be.png)

**Comment by rupav** [comment]
Good spot @praveenojha33 , found on mobile device too,:
![screenshot_20180203-124128](https://user-images.githubusercontent.com/20624380/35764089-cf05d6e6-08df-11e8-8427-930f2d6d6a8d.jpg)
Are you working on it? Can I work on it ?

**Comment by praveenojha33** [comment]
@rupav I have fixed it, I will make a PR soon.
