### ISSUE TITLE
Implementation of themes in Loklak_Search

### ISSUE THREAD

**Issue by praveenojha33** [fossasia/loklak_search#647]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
It does not have themes option as we have in Susper.com

**Expected behavior:**
Attractive new themes can be implemented in Loklak Search.

**Screenshots of the issue:**

**Comment by praveenojha33** [comment]
@singhpratyush @mariobehling @harshit98 please suggest your views.

**Comment by mariobehling** [comment]
Low priority and out of scope as there are many other things that need to be solved first.
