### ISSUE TITLE
locally not working on windows

### ISSUE THREAD

**Issue by rupav** [fossasia/loklak_search#648]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Follow commands on readme.md, to locally deploy loklak .
**Expected behavior:**

display of search engine
**Screenshots of the issue:**

Also, I had to explicitly install  node-sass using `npm install node_sass` command. 
![2018-02-03 2](https://user-images.githubusercontent.com/20624380/35763754-f679ce82-08d8-11e8-8694-9a2e5b74cf99.png)
Although webpack compiled successfully, `localhost:4200` only rendering favicon.ico
![2018-02-03 3](https://user-images.githubusercontent.com/20624380/35763759-1dc64e0c-08d9-11e8-95de-af0308df6ce6.png)

**Comment by rupav** [comment]
@fossasia/loklak please help.

**Comment by praveenojha33** [comment]
@rupav Can you please post the output of console

**Comment by rupav** [comment]
Here you go @praveenojha33 
![2018-02-03 4](https://user-images.githubusercontent.com/20624380/35765094-672ad45a-08e3-11e8-8d00-e852717b8091.png)

**Comment by simsausaurabh** [comment]
which node and npm version are you using ?

**Comment by rupav** [comment]
![2018-02-04 1](https://user-images.githubusercontent.com/20624380/35776017-8d19c3a6-09ba-11e8-949a-8afb507ddf98.png)

**Comment by simsausaurabh** [comment]
Use node v6.9.1. Install it using: `npm install v6.9.1`

**Comment by rupav** [comment]
command is correct? error shows up
latest version is 5.6.0
![2018-02-04 2](https://user-images.githubusercontent.com/20624380/35776070-9d2c1a5e-09bb-11e8-82ae-f7aa32a389ce.png)

**Comment by praveenojha33** [comment]
@rupav have you installed angular material.

**Comment by rupav** [comment]
yes @praveenojha33

**Comment by praveenojha33** [comment]
@rupav I suffered from a similar issue but output of console was different in my case.

**Comment by rupav** [comment]
oh ok @praveenojha33 ,I am new to js, that's why having trouble. As suggested, will install nvm and then try again.

**Comment by simsausaurabh** [comment]
@rupav any updates? Anyway, it is more favourable to use Ubuntu as working environment.

**Comment by rupav** [comment]
I never tried with nvm later, moved to Ubuntu now, you can close this issue :+1:

**Comment by simsausaurabh** [comment]
I don't have right access, please close this issue.

**Comment by praveenojha33** [comment]
@rupav Please close this.
