### ISSUE TITLE
Optimised Import

### ISSUE THREAD

**Issue by yashLadha** [fossasia/loklak_search#650]
Currently the project has waste import statements in file that really is of no use. This issue will the reformat the code structure by removing unused imports.

**Comment by Orbiter** [comment]
I cannot approve huge code changes like this. Please do not to attempt to do a "change everything". This mostly creates code conflicts for concurrent pull requests and resolving them is time costly. Furthermore large changes like this have the potential to include unwanted bugs. That is very commonly the case, even if the author 'just' intended to remove 'only' spaces and do a reformatting.
