### ISSUE TITLE
Migrating from Bower to NPM/Yarn

### ISSUE THREAD

**Issue by simsausaurabh** [fossasia/loklak_search#658]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

- Bower is on its way out, although Bower is still being maintained, Bower maintainers recommend not using Bower anymore and use the combination Yarn + Webpack.
- loklak_search runs on npm, so ```bower``` needs to be removed.

**Expected behavior:**

Project should migrate to npm(which it is)/Yarn

**Why Yarn?**
- Yarn will cache dependencies so subsequent installs can be done without re-downloading. This even works without an internet connection.
- Yarn has threads i.e. even without caching, Yarn is faster due to parallelization.
- for a mere reference:

command  | time (in seconds)
--------------- | -------------
npm install | 155s
yarn (cold cache) | 53s
yarn (warm cache) | 13s

This issue can be broken down into two parts:
- Removing bower
- Replacing npm with yarn

**Comment by simsausaurabh** [comment]
@singhpratyush please suggest, shall I proceed further?

**Comment by singhpratyush** [comment]
@simsausaurabh: What are the places where we need to remove Bower? Can you please provide links?

**Comment by simsausaurabh** [comment]
All occurrences of bower which we get using: ```git grep 'bower'``` in the root directory of the repo locally.

**Comment by singhpratyush** [comment]
Sure. Please proceed with it.

**Comment by simsausaurabh** [comment]
Thanks @singhpratyush, working on it. :+1:
