### ISSUE TITLE
Implement Accounts using Firebase

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#666]
As we did not have enough resources to set up our own accounting Firebase seems like a good solution to move forward.

Please implement an accounts system using Firebase. Use the free tier of Firebase to start with.

**Comment by simsausaurabh** [comment]
I would like to work on it.

**Comment by singhpratyush** [comment]
@mariobehling: What are the exact requirements from this feature? What are the services that we need to implement (e.g. Twitter, Google Plus, etc.)?

Will this be used to post Tweets from the loklak.org?

**Comment by Serkan-devel** [comment]
Can't this feature be scrapped entirely? It might be then easier to take down accounts over those centralized and poprietary endpoints by major corporations.
