### ISSUE TITLE
Broken search result

### ISSUE THREAD

**Issue by vayupranaditya** [fossasia/loklak_search#673]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Recently, hashtags and mentions show multiple times instead of the number they should show.

**Expected behavior:**

Hashtags and mentions should show exact the number they're posted.

**Screenshots of the issue:**

real tweet:
![issue1_1](https://user-images.githubusercontent.com/32421251/37240147-481c3a7e-247a-11e8-9f6c-8d4a5225735c.png)

loklak search result:
![issue1_2](https://user-images.githubusercontent.com/32421251/37240148-4854b304-247a-11e8-801c-cc256b0a7b40.png)

loklak api JSON result:
`"statuses": "text": "hashtag, video, links, audio, images, hosts, mention #vayu #vayu2 #vayu3 , [video], https://google.com, [audio], [host], @vayu_pranaditya @Google @Twitter @Google @Twitter"`

I think I could work on this

Edit:
**I couldn't work on this due to a problem in my pc.**

**Comment by singhpratyush** [comment]
@vayupranaditya: Sure, please proceed with this.

**Comment by vayupranaditya** [comment]
I'm sorry, I couldn't work on this due to a problem in my pc.
cc: @singhpratyush

**Comment by singhpratyush** [comment]
No problem :smile:. You can work on it now.

**Comment by singhpratyush** [comment]
@vayupranaditya: Are you working still working on this? Please let us know if you are facing any issues.
