### ISSUE TITLE
in README.md angular-cli failed to install when not using sudo

### ISSUE THREAD

**Issue by vayupranaditya** [fossasia/loklak_search#679]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

In README.md, failed to install angular-cli when not using `sudo`

**Expected behavior:**

angular-cli installed successfully

**Comment by praveenojha33** [comment]
@vayupranaditya This is not an issue it.It is requirement of your system.

**Comment by simsausaurabh** [comment]
Seems to work, @singhpratyush @sudheesh001 @hemantjadon this can be closed now.
