### ISSUE TITLE
CI setup for the repository

### ISSUE THREAD

**Issue by hemantjadon** [fossasia/loklak_search#7]
@mariobehling 
Hi sir,
As I am able to see the Travis CI is not enabled for this repository, please look into that.
Also Circle CI is failing on builds and throwing some errors (due to absence of .circle.yml, i suppose).
The codecov is still showing `unknown`(don't know the reason).

Also i think direct merge to `gh-pages` should not be there, I mean there must be another branch for development (as mentioned in `readme.md`) so that production and development code remains segregated.

**Comment by mariobehling** [comment]
We can make the process more advanced when there is more code and functionality. Please help to get this project going and we will establish a development process. We need code at the moment and less of a process. This project is at the beginning. Thanks.
