### ISSUE TITLE
500 for api.loklak.org request from 2018.opentechsummit.net

### ISSUE THREAD

**Issue by maxlorenz** [fossasia/loklak_search#701]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Getting `https://api.loklak.org/api/search.json?q=loklak&callback=__ng_jsonp__.__req11.finished&minified=true&source=all&maximumRecords=20&timezoneOffset=-120&startRecord=1&fields=created_at,screen_name,mentions,hashtags&limit=10` yields a 502 error.

Just calling `https://api.loklak.org/` gives a timeout

**Expected behavior:**
The query should return a useful json response, `https://api.loklak.org/` should return something

**Comment by singhpratyush** [comment]
@maxlorenz: It seems to be working now. 

Also, do you really need aggregations in the response? Queries with aggregations take longer to get a response.

**Comment by maxlorenz** [comment]
@singhpratyush thanks, everything is indeed fine. I don't know about the aggregation as this is an example taken from the OpenTech 2018 website. It works now, tweets are shown
