### ISSUE TITLE
The responsive design technology is not mentioned in the technology stack

### ISSUE THREAD

**Issue by sathiraumesh** [fossasia/loklak_search#710]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

BootStrap 3.3.2 should is not  mentioned
**Expected behavior:**

BootStrap 3.3.2 should be mentioned
**Screenshots of the issue:**

**Comment by simsausaurabh** [comment]
@mariobehling this issue can be closed now, it has been solved.

@sathiraumesh please follow https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/ and always reference the issue in PR which should automatically close the respective issue on merging of PR.

**Comment by sathiraumesh** [comment]
ok 👍
