### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by Rupeshiya** [fossasia/loklak_search#712]
**I'm submitting a ...**
- [x] bug report

**Current behavior:**
Dependency badge is not appearing in README.md

**Expected behavior:**
Dependency status badge should appear in README.md

**Screenshots of the issue:**
![screenshot 23](https://user-images.githubusercontent.com/31209617/40270249-2c46245e-5ba7-11e8-8264-006eb915c933.png)

**Comment by Rupeshiya** [comment]
@simsausaurabh  should I fix this issue.?

**Comment by simsausaurabh** [comment]
@Rupeshiya sure go ahead, but it seems there is some other problem may be due to the migration of Gemnasium.

**Comment by Rupeshiya** [comment]
@simsausaurabh can you suggest ,how it should be like ?

**Comment by simsausaurabh** [comment]
@Rupeshiya I am not sure about it. Currently I am working on high priority issues.

**Comment by simsausaurabh** [comment]
@Rupeshiya any updates?

**Comment by Rupeshiya** [comment]
@simsausaurabh  I can add the badge but I want to take some idea from you guys as well so that there can not be any conflicts and issue will be solved.
Till now I have not got any updates.So need your help.

**Comment by simsausaurabh** [comment]
This issue references to the invisibility of badge. See if you can solve this issue first. The possibility could be that many of the developers are not free everytime, so they might not be able to help. As of now, I am working on other high priority issues. Please try to solve this issue and further issues can be solved in another patch.

**Comment by simsausaurabh** [comment]
There are a lot of issues still opened try to solve them, you can solve this one easily.

**Comment by Rupeshiya** [comment]
okay @simsausaurabh  I am going to follow  your advice. 
Thanks.
