### ISSUE TITLE
Implement terms page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#73]
The page at http://loklak.fossasia.org/terms currently does not hold information. Please implement the page as a terms of reference page in the same design as the other info pages, but without the picture. See below. The text for the terms is here: https://docs.google.com/document/d/1-w7C-PySdw1c8J2WbkBaqRRXjeXj3qFUoyDqAMbhlig

![screenshot from 2016-10-27 18 30 49](https://cloud.githubusercontent.com/assets/1583873/19791333/ec3601ec-9c74-11e6-8597-5ab3345f5908.png)

Also compare to: https://www.google.com/intl/en/policies/terms/

**Comment by pranayyelugam** [comment]
@mariobehling I would like to do this

**Comment by mariobehling** [comment]
Ok great, go for it.

**Comment by mariobehling** [comment]
@pranayyelugam Thanks for setting up this site. Please ensure left side top "Terms of Service" heading is aligned same as the logo.

Please also ensure width is same as on this site: Also compare to: https://www.google.com/intl/en/policies/terms/

**Comment by jajodiaraghav** [comment]
I wonder why this issue is still open. Is there anything else that needs to be done?

**Comment by hemantjadon** [comment]
@mariobehling any updates required in this?
