### ISSUE TITLE
Add Icon to all pages of loklak site

### ISSUE THREAD

**Issue by sandmanx** [fossasia/loklak_search#75]
Currently only one webpage has the loklak icon. http://api.loklak.org/

![rsz_screenshot_from_2016-10-28_22-21-32](https://cloud.githubusercontent.com/assets/14184381/19814909/f48cdea8-9d5d-11e6-98b9-ab58f61ddb6f.png)

I suggest adding the icon to every webpage in loklak search.

**Comment by jig08** [comment]
@sandmanx would you like to take up this issue ?

**Comment by sandmanx** [comment]
Yes

**Comment by mariobehling** [comment]
@sandmanx Not sure, how this would look like exactly. Please provide screenshots and links to a sample site as you progress.

**Comment by sandmanx** [comment]
@mariobehling I don't know what was the problem, but now the loklak icon is visible now on all the pages of loklak website. You can close the issue now.
![screenshot from 2016-11-05 01-13-42](https://cloud.githubusercontent.com/assets/14184381/20020069/52e24654-a2f5-11e6-9f3b-dd58e12e59b1.png)

![screenshot from 2016-11-05 01-15-43](https://cloud.githubusercontent.com/assets/14184381/20020076/5dad14ba-a2f5-11e6-975d-08464170fb07.png)
