### ISSUE TITLE
changing the alternate text for an image

### ISSUE THREAD

**Issue by pranayyelugam** [fossasia/loklak_search#78]
The alternate text for the image loklak_banner_206x45 is set as "Dispute Bills" as shown in the image below.

I think it should be something related to loklak.
![capture](https://cloud.githubusercontent.com/assets/16484527/19832476/f9883c56-9e41-11e6-9bd9-615f3fa2328c.PNG)

**Comment by rishiraj824** [comment]
Fixed in the latest commit in  the pull request. #76 & #78

**Comment by pranayyelugam** [comment]
This issue was fixed via #86  . I am closing it.
