### ISSUE TITLE
Ensure bottom menu sticks to bottom on search page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#81]
If there are just a few results the bottom menu currently does not show up on the absolute browser window bottom.

Please ensure the bottom is on the actual bottom area if this happens.

![screenshot from 2016-10-31 09 45 48](https://cloud.githubusercontent.com/assets/1583873/19862743/d3eac262-9f4e-11e6-8735-a408100b127d.png)

**Comment by hemantjadon** [comment]
@mariobehling 
I know this issue since i wrote this, its the issue with peeking(not found) and non-peeking footer(generally) and will try to fix it asap.

**Comment by hemantjadon** [comment]
Fixed this issue for the feed Page in PR #126.
