### ISSUE TITLE
Ensure bottom menu items link to top of pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#85]
Clicking on bottom links does not bring a user to the top of pages, e.g. if I am on the contact page (http://loklak.fossasia.org/contact) and I click on "Terms" I get into the middle of that page.

Please implement the expected behavior and open the new page on the top.

**Comment by hemantjadon** [comment]
@mariobehling This might be an issue with `routerlink` directive, I will go through the documentation once, and check it out.

**Comment by Achint08** [comment]
Hello @mariobehling  .There is another way using "router.events.subscribe" . Tell me if this works or do I make another pull request?

**Comment by mariobehling** [comment]
Yes, could be a good solution.
