### ISSUE TITLE
Overlapping links in sidebar

### ISSUE THREAD

**Issue by praveenojha33** [fossasia/loklak_search#885]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
For some queries the links in sidebar(Top hashtags) overlaps with the boundary of sidebar.
**Expected behavior:**
Links should not overlap with the boundary. 
**Screenshots of the issue:**
![image](https://user-images.githubusercontent.com/25537606/43356987-0196f094-9298-11e8-96bd-137fef9b0cff.png)

**Comment by simsausaurabh** [comment]
@praveenojha33 We have an issue for this overflowing text here: #810. Please close this issue.

**Comment by praveenojha33** [comment]
Duplicate of #810
