### ISSUE TITLE
Add hardcoded LOGO URLs inside config file

### ISSUE THREAD

**Issue by simsausaurabh** [fossasia/loklak_search#900]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

LOGO URLs are hardcoded.

**Expected behavior:**

They need to be added into the url config file.

**Screenshots of the issue:**

**Comment by Rupeshiya** [comment]
@simsausaurabh bhaiya  I would like to fix this but where is screenshot of issue and where to add ??

**Comment by simsausaurabh** [comment]
@Rupeshiya You need to add the hardcoded URLs i.e. the links of logos, etc. into the config file.

**Comment by Rupeshiya** [comment]
@simsausaurabh  can not find out config file and url of the logo ,can you provide link ?

**Comment by championpaddler** [comment]
Claiming it.
