### ISSUE TITLE
Shift Profile section above Top Twitterers and Top hashtags

### ISSUE THREAD

**Issue by praveenojha33** [fossasia/loklak_search#915]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Currently whenever a search is made using `from: user_name` the profile section of the user appears below the top twitterers and top hashtags section.Since its results are more relevant it should be above Top Twitterers and Top hashtags.
**Expected behavior:**
Please shift Profile section above Top Twitterers and Top hashtags

**Screenshots of the issue:**
![image](https://user-images.githubusercontent.com/25537606/44684169-06aa2480-aa66-11e8-8f04-cc165eceb2b7.png)

**Comment by shreyanshdwivedi** [comment]
@praveenojha33 I want to work on this. Can I proceed?
