### ISSUE TITLE
Add Contact Us in the grid menu

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/loklak_search#918]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Feature Description**
Add contact-us in the grid menu.
![grid-menu](https://user-images.githubusercontent.com/33062425/45754858-6f865600-bc3a-11e8-89e4-c763168ec28e.png)

**Comment by rajvaibhavdubey** [comment]
I'm working on this.

**Comment by praveenojha33** [comment]
@rajvaibhavdubey Is it really needed ? We already have Contact Us link at the home page.

**Comment by rajvaibhavdubey** [comment]
@praveenojha33 I think that it is a bit more appropriate to have the contact-us link in the menu grid, This will also help in maintaining the similarity across projects.
Below is a screenshot of susper
![grid](https://user-images.githubusercontent.com/33062425/45755740-cab94800-bc3c-11e8-9e06-893a2ebc3314.png)
This would look much better.
Please correct me if I'm wrong.
Thankyou :smile:

**Comment by praveenojha33** [comment]
@rajvaibhavdubey The service menu provides links to different services. We want to keep design similar to 
Google. Please compare it with Google. @simsausaurabh What are your views ?

**Comment by simsausaurabh** [comment]
@rajvaibhavdubey Yes, mainly the service-box is for the links of services provided by FOSSASIA and Loklak, so having `Contact Us` which is a mere endpoint to the one of the component of loklak_search won't be really good. We would not actually want to fill the service-box with such stuff

@rajvaibhavdubey There are a lot of high priority issues/bugs currently opened, please work on them. I hope it helps :+1:
