### ISSUE TITLE
Add infobox to search results on right side on result page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#92]
Services like Duckduckgo and Google create an infobox to search results. 

* [x] Please add a similar sidebar to search results (as was shown in the webclient wall before).
* [x] Implement similar clean design with white background and gray border

Sample infobox at Google

![screenshot from 2016-11-03 11 41 53](https://cloud.githubusercontent.com/assets/1583873/19955280/c714c0ec-a1ba-11e6-9b35-22459228faed.png)

Example of info box on loklak webclient prototype

![screenshot from 2016-11-03 11 39 30](https://cloud.githubusercontent.com/assets/1583873/19955292/da6bd626-a1ba-11e6-8b7d-8e6b8a0ca564.png)

**Comment by rishiraj824** [comment]
@mariobehling Can you please explain, for which type of queries would the infobox come up if they are to show Top Twitterers and Top Hashtags. eg. If the query has 'hello world' then the Top Twitterers with the name 'hello world' would come and similarly Top Hashtags containing 'hello world' ? Also, where is this available in the API ?

**Comment by hemantjadon** [comment]
@rishiraj824 this can be good start.
@Orbiter your inputs on how this can be extracted from API.

**Comment by mariobehling** [comment]
@rishiraj824 @hemantjadon All required info for that can be requested through the APIs as documented here: http://loklak.org/api.html

It was done on the webclient before: https://github.com/fossasia/loklak_webclient

**Comment by rishiraj824** [comment]
@mariobehling I'd like to go ahead with this issue.

**Comment by Achint08** [comment]
can I work on this now?

**Comment by uttu357** [comment]
@mariobehling This issue can be closed now.
