### ISSUE TITLE
Adding Badgeyay link to FOSSASIA Projects Menu

### ISSUE THREAD

**Issue by championpaddler** [fossasia/loklak_search#922]
**I'm submitting a ...**
- [x] feature request

**Current behavior:**

Badgeyay is missing.
Badgeyay is missing
**Expected behavior:**

**Expected behavior:**

Bageyay should be present 
**Screenshots of the issue:**

![screenshot from 2018-10-05 09-50-16](https://user-images.githubusercontent.com/17084322/46515880-18ac8d80-c884-11e8-84d2-4c3ba858e9cd.png)

Will Work on issue??
Yes

**Comment by championpaddler** [comment]
@simsausaurabh Badgeyay Link is present in the development branch and not in master.

**Comment by simsausaurabh** [comment]
@sk9331657 It will get automatically fixed on next release (merge of development branch into master branch).
