### ISSUE TITLE
Security vulnerabilities in some dependencies 

### ISSUE THREAD

**Issue by simsausaurabh** [fossasia/loklak_search#931]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

There are some security vulnerabilities in some dependencies.

**Expected behavior:**

It should be fixed asap.

Affected dependencies: ```cryptiles```, ```timespan```, ```url-parse```, ```merge```.

**Comment by sakshee-19** [comment]
@simsausaurabh I am working on it :+1:

**Comment by championpaddler** [comment]
@sakshee-19  Are u still working on this??

**Comment by sakshee-19** [comment]
@sk9331657 Yes, I have almost fixed it. I will send a patch by tonight.
