### ISSUE TITLE
Improving Terms and Privacy page UI

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/loklak_search#937]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Currently `Terms` and `Privacy` page is not user friendly at all. We need to improve it by adding sidebar having links to different section.

**Expected behavior:**

We can expect something like Google `Terms` and `Privacy` page.

- [ ] Terms Page
- [ ] Privacy Page

**Screenshots of the issue:**

**Current**
![screenshot_2018-12-14 loklak search - distributed search for twitter and social media with peer to peer technology](https://user-images.githubusercontent.com/25428397/49998320-ffc60400-ffb9-11e8-813a-7f3c37f45c6d.png)

**Expected**
![screenshot_2018-12-12 google terms of service privacy terms google](https://user-images.githubusercontent.com/25428397/49998352-0e142000-ffba-11e8-9a98-8e75b7d2c5a9.png)

**Will work on the issue??**

Yes, I'm working on it.

**Comment by shreyanshdwivedi** [comment]
@praveenojha33 @simsausaurabh I would like to work on this. I think it's pretty relevant issue and we need this improvement. Should I proceed?

**Comment by simsausaurabh** [comment]
Yes, you can work on it.
