### ISSUE TITLE
Security vulnerabilities: cryptiles & timespan 

### ISSUE THREAD

**Issue by simsausaurabh** [fossasia/loklak_search#947]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

There are some security vulnerabilities present in the project related to cryptiles and timespan.

**Expected behavior:**

It should not be present.

**Screenshots of the issue:**

**Will work on the issue??**

No

**Comment by sakshee-19** [comment]
I working on this issue 👍
