### ISSUE TITLE
Security vulnerability in Webpack-dev-server

### ISSUE THREAD

**Issue by simsausaurabh** [fossasia/loklak_search#952]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Github recently alerted Webpack-dev-server as a security vulnerability.

**Expected behavior:**

It should be fixed.

**Screenshots of the issue:**

**Will work on the issue??**

No

**Comment by sakshee-19** [comment]
I am working on it :+1:
