### ISSUE TITLE
Add newer projects to dropdown and minor UI fixes

### ISSUE THREAD

**Issue by abhijeetyadav82** [fossasia/loklak_search#955]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

The dropdown has many bugs like
- Badgeyay icon is stretched for some screemsizes
- Newer projects of fossasia like meilix need to added in the dropdown

**Screenshots of the issue:**

![screenshot from 2019-02-05 08-32-16](https://user-images.githubusercontent.com/32612741/52238855-0b1b1900-28f3-11e9-90ac-021ee0ec622e.png)

**Will work on the issue??**

Yes

**Comment by Aaryan-kapur** [comment]
if this is available, I'd love to start working on this!
