### ISSUE TITLE
Text instead of link in settings menu

### ISSUE THREAD

**Issue by abhijeetyadav82** [fossasia/loklak_search#957]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

In the settings menu there must be links present instead of text for the urls. 
**Expected behavior:**

Clicking on the given link would redirect to its url.
**Screenshots of the issue:**

![loklak_setting](https://user-images.githubusercontent.com/32612741/52363130-0cba1d80-2a68-11e9-95c7-860f3024cd3d.png)
![loklak_setting1](https://user-images.githubusercontent.com/32612741/52363170-1f345700-2a68-11e9-9b72-daa9aeb275ca.png)
![loklak_setting2](https://user-images.githubusercontent.com/32612741/52363189-2b201900-2a68-11e9-877a-925a73ccd93e.png)
![loklak_setting3](https://user-images.githubusercontent.com/32612741/52363198-31ae9080-2a68-11e9-959d-fd0964c05adf.png)

**Will work on the issue??**

Yes

**Comment by kpulkit29** [comment]
I want to work on this issue

**Comment by simsausaurabh** [comment]
@kpulkit29 Go ahead 👍

**Comment by kpulkit29** [comment]
@simsausaurabh  Kindly look at it
