### ISSUE TITLE
Implement @user in search results as links to @user search within loklak_search

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#98]
Currently @user links in search results link to the list of @user results on twitter.

The expected behavior is that "@user" link to the search result page of loklak_search.

Note: In order to provide all relevant data of a user, we will add an infobox with user data on the right handside at a later point.

**Comment by hemantjadon** [comment]
Do we want to have all the results (tweets) from the respective user here?

If so should `from:<username>` be used as a query

**Comment by mariobehling** [comment]
@hemantjadon Yes, as this is the way Twitter works, it should work the same e.g. http://loklak.fossasia.org/search?query=from:mariobehling
