### ISSUE TITLE
Some hashtags not showing to internal search

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#99]
![screenshot from 2016-11-03 18 23 26](https://cloud.githubusercontent.com/assets/1583873/19962461/b234c0d6-a1f2-11e6-8c9d-38fceca82aab.png)

Please ensure all hashtags show to internal search.

The tag #openwrtsummit shows to twitter instead of internal search.

**Comment by hemantjadon** [comment]
@mariobehling 
This seems to be working fine, If all links are not working It might be a `caching` issue, A `hard refresh` is needed after every site update.

* Do `ctrl(cmd)+shift+R` or open `devtools` then press the combination.

* A issue can be opened to address to address such caching issue.

**Comment by mariobehling** [comment]
Ok, hard refresh does not work always. It might be cached online by cloudflare. Issue goes away in private mode. Cheers.
